// @generated by `cargo run -p xtask -- gen` from specs/youtube.json — do not edit by hand.
#![allow(clippy::all)]
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    non_snake_case,
    rustdoc::all
)]

use crate::core::{Client, Error, Method, QueryParams, Result};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;

/// Handle for the `youtube` platform. Obtain via [`crate::ScrapeBadger::youtube`].
#[derive(Clone)]
pub struct Youtube {
    client: Client,
}

impl Youtube {
    pub(crate) fn new(client: Client) -> Self {
        Self { client }
    }

    /// Access the underlying transport client.
    pub fn client(&self) -> &Client {
        &self.client
    }

    /// Keyword suggestions
    ///
    /// Return YouTube keyword autocomplete suggestions.
    /// `GET /v1/youtube/autocomplete`
    pub async fn autocomplete(&self, params: AutocompleteParams) -> Result<Value> {
        let path = "/v1/youtube/autocomplete".to_string();
        let mut q = QueryParams::new();
        q.opt("query", params.query.as_ref());
        q.opt("gl", params.gl.as_ref());
        q.opt("hl", params.hl.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Video categories
    /// `GET /v1/youtube/categories`
    pub async fn categories(&self, params: CategoriesParams) -> Result<Value> {
        let path = "/v1/youtube/categories".to_string();
        let mut q = QueryParams::new();
        q.opt("gl", params.gl.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Resolve handle/URL to id
    /// `GET /v1/youtube/channels/resolve`
    pub async fn channels_resolve(&self, params: ChannelsResolveParams) -> Result<Value> {
        let path = "/v1/youtube/channels/resolve".to_string();
        let mut q = QueryParams::new();
        q.opt("handle", params.handle.as_ref());
        q.opt("url", params.url.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get channel detail
    ///
    /// Channel detail (accepts a UC id, @handle, or custom URL).
    /// `GET /v1/youtube/channels/{channel_id}`
    pub async fn get_channel(
        &self,
        channel_id: impl AsRef<str>,
        params: GetChannelParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/youtube/channels/{channel_id}",
            channel_id = channel_id.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("gl", params.gl.as_ref());
        q.opt("hl", params.hl.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Channel about
    /// `GET /v1/youtube/channels/{channel_id}/about`
    pub async fn channel_about(
        &self,
        channel_id: impl AsRef<str>,
        params: ChannelAboutParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/youtube/channels/{channel_id}/about",
            channel_id = channel_id.as_ref()
        );
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Community posts
    /// `GET /v1/youtube/channels/{channel_id}/community`
    pub async fn channel_community(
        &self,
        channel_id: impl AsRef<str>,
        params: ChannelCommunityParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/youtube/channels/{channel_id}/community",
            channel_id = channel_id.as_ref()
        );
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Channel playlists
    /// `GET /v1/youtube/channels/{channel_id}/playlists`
    pub async fn channel_playlists(
        &self,
        channel_id: impl AsRef<str>,
        params: ChannelPlaylistsParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/youtube/channels/{channel_id}/playlists",
            channel_id = channel_id.as_ref()
        );
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Search within a channel
    /// `GET /v1/youtube/channels/{channel_id}/search`
    pub async fn channel_search(
        &self,
        channel_id: impl AsRef<str>,
        params: ChannelSearchParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/youtube/channels/{channel_id}/search",
            channel_id = channel_id.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("query", params.query.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Channel shorts
    /// `GET /v1/youtube/channels/{channel_id}/shorts`
    pub async fn channel_shorts(
        &self,
        channel_id: impl AsRef<str>,
        params: ChannelShortsParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/youtube/channels/{channel_id}/shorts",
            channel_id = channel_id.as_ref()
        );
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Channel streams
    /// `GET /v1/youtube/channels/{channel_id}/streams`
    pub async fn channel_streams(
        &self,
        channel_id: impl AsRef<str>,
        params: ChannelStreamsParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/youtube/channels/{channel_id}/streams",
            channel_id = channel_id.as_ref()
        );
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Subscriber count (fast)
    /// `GET /v1/youtube/channels/{channel_id}/subscriber_count`
    pub async fn channel_subscriber_count(
        &self,
        channel_id: impl AsRef<str>,
        params: ChannelSubscriberCountParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/youtube/channels/{channel_id}/subscriber_count",
            channel_id = channel_id.as_ref()
        );
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Channel videos
    /// `GET /v1/youtube/channels/{channel_id}/videos`
    pub async fn channel_videos(
        &self,
        channel_id: impl AsRef<str>,
        params: ChannelVideosParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/youtube/channels/{channel_id}/videos",
            channel_id = channel_id.as_ref()
        );
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Videos under a hashtag
    /// `GET /v1/youtube/hashtags/{tag}`
    pub async fn hashtag(&self, tag: impl AsRef<str>, params: HashtagParams) -> Result<Value> {
        let path = format!("/v1/youtube/hashtags/{tag}", tag = tag.as_ref());
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Guest home feed
    /// `GET /v1/youtube/home`
    pub async fn home(&self, params: HomeParams) -> Result<Value> {
        let path = "/v1/youtube/home".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// UI languages
    /// `GET /v1/youtube/languages`
    pub async fn languages(&self, params: LanguagesParams) -> Result<Value> {
        let path = "/v1/youtube/languages".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Supported markets
    /// `GET /v1/youtube/markets`
    pub async fn markets(&self, params: MarketsParams) -> Result<Value> {
        let path = "/v1/youtube/markets".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get a mix / radio queue
    /// `GET /v1/youtube/mixes/{playlist_id}`
    pub async fn get_mix(
        &self,
        playlist_id: impl AsRef<str>,
        params: GetMixParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/youtube/mixes/{playlist_id}",
            playlist_id = playlist_id.as_ref()
        );
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Search YouTube Music
    /// `GET /v1/youtube/music/search`
    pub async fn music_search(&self, params: MusicSearchParams) -> Result<Value> {
        let path = "/v1/youtube/music/search".to_string();
        let mut q = QueryParams::new();
        q.opt("query", params.query.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// oEmbed metadata
    /// `GET /v1/youtube/oembed`
    pub async fn oembed(&self, params: OembedParams) -> Result<Value> {
        let path = "/v1/youtube/oembed".to_string();
        let mut q = QueryParams::new();
        q.opt("url", params.url.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get playlist detail
    /// `GET /v1/youtube/playlists/{playlist_id}`
    pub async fn get_playlist(
        &self,
        playlist_id: impl AsRef<str>,
        params: GetPlaylistParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/youtube/playlists/{playlist_id}",
            playlist_id = playlist_id.as_ref()
        );
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Playlist items page
    /// `GET /v1/youtube/playlists/{playlist_id}/items`
    pub async fn playlist_items(
        &self,
        playlist_id: impl AsRef<str>,
        params: PlaylistItemsParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/youtube/playlists/{playlist_id}/items",
            playlist_id = playlist_id.as_ref()
        );
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get a community post
    /// `GET /v1/youtube/posts/{post_id}`
    pub async fn get_post(&self, post_id: impl AsRef<str>, params: GetPostParams) -> Result<Value> {
        let path = format!("/v1/youtube/posts/{post_id}", post_id = post_id.as_ref());
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Community post comments
    /// `GET /v1/youtube/posts/{post_id}/comments`
    pub async fn post_comments(
        &self,
        post_id: impl AsRef<str>,
        params: PostCommentsParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/youtube/posts/{post_id}/comments",
            post_id = post_id.as_ref()
        );
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Content regions
    /// `GET /v1/youtube/regions`
    pub async fn regions(&self, params: RegionsParams) -> Result<Value> {
        let path = "/v1/youtube/regions".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Search YouTube
    ///
    /// Search videos / channels / playlists with the full filter matrix.
    /// `GET /v1/youtube/search`
    pub async fn search(&self, params: SearchParams) -> Result<Value> {
        let path = "/v1/youtube/search".to_string();
        let mut q = QueryParams::new();
        q.opt("query", params.query.as_ref());
        q.opt("type", params.type_.as_ref());
        q.opt("sort_by", params.sort_by.as_ref());
        q.opt("upload_date", params.upload_date.as_ref());
        q.opt("duration", params.duration.as_ref());
        q.opt("features", params.features.as_ref());
        q.opt("gl", params.gl.as_ref());
        q.opt("hl", params.hl.as_ref());
        q.opt("continuation", params.continuation.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Shorts by sound
    /// `GET /v1/youtube/shorts/by_sound/{sound_id}`
    pub async fn shorts_by_sound(
        &self,
        sound_id: impl AsRef<str>,
        params: ShortsBySoundParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/youtube/shorts/by_sound/{sound_id}",
            sound_id = sound_id.as_ref()
        );
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get a Short
    /// `GET /v1/youtube/shorts/{video_id}`
    pub async fn get_short(
        &self,
        video_id: impl AsRef<str>,
        params: GetShortParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/youtube/shorts/{video_id}",
            video_id = video_id.as_ref()
        );
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Trending videos
    /// `GET /v1/youtube/trending`
    pub async fn trending(&self, params: TrendingParams) -> Result<Value> {
        let path = "/v1/youtube/trending".to_string();
        let mut q = QueryParams::new();
        q.opt("gl", params.gl.as_ref());
        q.opt("type", params.type_.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Trending shorts
    /// `GET /v1/youtube/trending/shorts`
    pub async fn trending_shorts(&self, params: TrendingShortsParams) -> Result<Value> {
        let path = "/v1/youtube/trending/shorts".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Batch video detail
    /// `POST /v1/youtube/videos/batch`
    pub async fn videos_batch(&self, params: VideosBatchParams) -> Result<Value> {
        let path = "/v1/youtube/videos/batch".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::POST, &path, &query, body).await
    }

    /// Get video detail
    ///
    /// Full video detail — merged player + next (likes, comments, chapters, related).
    /// `GET /v1/youtube/videos/{video_id}`
    pub async fn get_video(
        &self,
        video_id: impl AsRef<str>,
        params: GetVideoParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/youtube/videos/{video_id}",
            video_id = video_id.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("gl", params.gl.as_ref());
        q.opt("hl", params.hl.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// List caption tracks
    /// `GET /v1/youtube/videos/{video_id}/captions`
    pub async fn video_captions(
        &self,
        video_id: impl AsRef<str>,
        params: VideoCaptionsParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/youtube/videos/{video_id}/captions",
            video_id = video_id.as_ref()
        );
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Video comments
    /// `GET /v1/youtube/videos/{video_id}/comments`
    pub async fn video_comments(
        &self,
        video_id: impl AsRef<str>,
        params: VideoCommentsParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/youtube/videos/{video_id}/comments",
            video_id = video_id.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("sort_by", params.sort_by.as_ref());
        q.opt("continuation", params.continuation.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Comment replies
    /// `GET /v1/youtube/videos/{video_id}/comments/{comment_id}/replies`
    pub async fn video_replies(
        &self,
        video_id: impl AsRef<str>,
        comment_id: impl AsRef<str>,
        params: VideoRepliesParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/youtube/videos/{video_id}/comments/{comment_id}/replies",
            video_id = video_id.as_ref(),
            comment_id = comment_id.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("continuation", params.continuation.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Live chat messages
    /// `GET /v1/youtube/videos/{video_id}/live_chat`
    pub async fn video_live_chat(
        &self,
        video_id: impl AsRef<str>,
        params: VideoLiveChatParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/youtube/videos/{video_id}/live_chat",
            video_id = video_id.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("continuation", params.continuation.as_ref());
        q.opt("replay", params.replay.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Related videos
    /// `GET /v1/youtube/videos/{video_id}/related`
    pub async fn video_related(
        &self,
        video_id: impl AsRef<str>,
        params: VideoRelatedParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/youtube/videos/{video_id}/related",
            video_id = video_id.as_ref()
        );
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Stream formats
    ///
    /// Stream/format metadata (best-effort; media URLs may be PO-token gated).
    /// `GET /v1/youtube/videos/{video_id}/streams`
    pub async fn video_streams(
        &self,
        video_id: impl AsRef<str>,
        params: VideoStreamsParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/youtube/videos/{video_id}/streams",
            video_id = video_id.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("client", params.client.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Video transcript
    /// `GET /v1/youtube/videos/{video_id}/transcript`
    pub async fn video_transcript(
        &self,
        video_id: impl AsRef<str>,
        params: VideoTranscriptParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/youtube/videos/{video_id}/transcript",
            video_id = video_id.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("language", params.language.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }
}

// ===== Models =====

/// Parameters for [`AutocompleteParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct AutocompleteParams {
    /// Partial query prefix
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gl: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hl: Option<String>,
}

/// Parameters for [`CategoriesParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct CategoriesParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gl: Option<String>,
}

/// Parameters for [`ChannelsResolveParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ChannelsResolveParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub handle: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

/// Parameters for [`GetChannelParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetChannelParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gl: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hl: Option<String>,
}

/// Parameters for [`ChannelAboutParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ChannelAboutParams {}

/// Parameters for [`ChannelCommunityParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ChannelCommunityParams {}

/// Parameters for [`ChannelPlaylistsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ChannelPlaylistsParams {}

/// Parameters for [`ChannelSearchParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ChannelSearchParams {
    /// Search keywords
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
}

/// Parameters for [`ChannelShortsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ChannelShortsParams {}

/// Parameters for [`ChannelStreamsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ChannelStreamsParams {}

/// Parameters for [`ChannelSubscriberCountParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ChannelSubscriberCountParams {}

/// Parameters for [`ChannelVideosParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ChannelVideosParams {}

/// Parameters for [`HashtagParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct HashtagParams {}

/// Parameters for [`HomeParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct HomeParams {}

/// Parameters for [`LanguagesParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct LanguagesParams {}

/// Parameters for [`MarketsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct MarketsParams {}

/// Parameters for [`GetMixParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetMixParams {}

/// Parameters for [`MusicSearchParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct MusicSearchParams {
    /// Search keywords
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
}

/// Parameters for [`OembedParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct OembedParams {
    /// A YouTube URL
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

/// Parameters for [`GetPlaylistParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetPlaylistParams {}

/// Parameters for [`PlaylistItemsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct PlaylistItemsParams {}

/// Parameters for [`GetPostParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetPostParams {}

/// Parameters for [`PostCommentsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct PostCommentsParams {}

/// Parameters for [`RegionsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct RegionsParams {}

/// Parameters for [`SearchParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct SearchParams {
    /// Search keywords
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    /// video|channel|playlist|movie|all
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "type")]
    pub type_: Option<String>,
    /// relevance|date|views|rating
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sort_by: Option<String>,
    /// hour|today|week|month|year
    #[serde(skip_serializing_if = "Option::is_none")]
    pub upload_date: Option<String>,
    /// short|medium|long
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration: Option<String>,
    /// hd,4k,360,vr180,3d,hdr,cc,subtitles,live
    #[serde(skip_serializing_if = "Option::is_none")]
    pub features: Option<String>,
    /// Content region (US, GB, DE…)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gl: Option<String>,
    /// UI language
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hl: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub continuation: Option<String>,
}

/// Parameters for [`ShortsBySoundParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ShortsBySoundParams {}

/// Parameters for [`GetShortParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetShortParams {}

/// Parameters for [`TrendingParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct TrendingParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gl: Option<String>,
    /// now|music|gaming|movies
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "type")]
    pub type_: Option<String>,
}

/// Parameters for [`TrendingShortsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct TrendingShortsParams {}

/// Parameters for [`VideosBatchParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct VideosBatchParams {}

/// Parameters for [`GetVideoParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetVideoParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gl: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hl: Option<String>,
}

/// Parameters for [`VideoCaptionsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct VideoCaptionsParams {}

/// Parameters for [`VideoCommentsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct VideoCommentsParams {
    /// top|newest
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sort_by: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub continuation: Option<String>,
}

/// Parameters for [`VideoRepliesParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct VideoRepliesParams {
    /// Replies continuation token
    #[serde(skip_serializing_if = "Option::is_none")]
    pub continuation: Option<String>,
}

/// Parameters for [`VideoLiveChatParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct VideoLiveChatParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub continuation: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub replay: Option<bool>,
}

/// Parameters for [`VideoRelatedParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct VideoRelatedParams {}

/// Parameters for [`VideoStreamsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct VideoStreamsParams {
    /// IOS|ANDROID|WEB
    #[serde(skip_serializing_if = "Option::is_none")]
    pub client: Option<String>,
}

/// Parameters for [`VideoTranscriptParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct VideoTranscriptParams {
    /// BCP-47 language code
    #[serde(skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
}
