// @generated by `cargo run -p xtask -- gen` from specs/redfin.json — do not edit by hand.
#![allow(clippy::all)]
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    non_snake_case,
    rustdoc::all
)]

use crate::core::{Client, Error, Method, QueryParams, Result};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;

/// Handle for the `redfin` platform. Obtain via [`crate::ScrapeBadger::redfin`].
#[derive(Clone)]
pub struct Redfin {
    client: Client,
}

impl Redfin {
    pub(crate) fn new(client: Client) -> Self {
        Self { client }
    }

    /// Access the underlying transport client.
    pub fn client(&self) -> &Client {
        &self.client
    }

    /// Get agent profile + listings
    ///
    /// Get a Redfin real-estate agent's profile and their active listings.
    /// `GET /v1/redfin/agent`
    pub async fn get_agent(&self, params: GetAgentParams) -> Result<Value> {
        let path = "/v1/redfin/agent".to_string();
        let mut q = QueryParams::new();
        q.opt("url", params.url.as_ref());
        q.opt("agent_id", params.agent_id.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Region/address suggestions
    ///
    /// Resolve a search term to Redfin regions/addresses.
    /// `GET /v1/redfin/autocomplete`
    pub async fn autocomplete(&self, params: AutocompleteParams) -> Result<Value> {
        let path = "/v1/redfin/autocomplete".to_string();
        let mut q = QueryParams::new();
        q.opt("query", params.query.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// List coverage markets
    ///
    /// List Redfin coverage regions (US).
    /// `GET /v1/redfin/markets`
    pub async fn list_markets(&self, params: ListMarketsParams) -> Result<Value> {
        let path = "/v1/redfin/markets".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get property detail by URL
    ///
    /// Get a single Redfin property's full detail by its home URL.
    /// `GET /v1/redfin/property`
    pub async fn get_property_by_url(&self, params: GetPropertyByUrlParams) -> Result<Value> {
        let path = "/v1/redfin/property".to_string();
        let mut q = QueryParams::new();
        q.opt("url", params.url.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get property detail
    ///
    /// Get a single Redfin property's full detail by its numeric propertyId.
    /// `GET /v1/redfin/property/{property_id}`
    pub async fn get_property(
        &self,
        property_id: impl AsRef<str>,
        params: GetPropertyParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/redfin/property/{property_id}",
            property_id = property_id.as_ref()
        );
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Search properties
    ///
    /// Search Redfin for for-sale / for-rent / recently-sold properties.
    /// `GET /v1/redfin/search`
    pub async fn search(&self, params: SearchParams) -> Result<Value> {
        let path = "/v1/redfin/search".to_string();
        let mut q = QueryParams::new();
        q.opt("location", params.location.as_ref());
        q.opt("page", params.page.as_ref());
        q.opt("sort", params.sort.as_ref());
        q.opt("price_min", params.price_min.as_ref());
        q.opt("price_max", params.price_max.as_ref());
        q.opt("beds_min", params.beds_min.as_ref());
        q.opt("baths_min", params.baths_min.as_ref());
        q.opt("home_type", params.home_type.as_ref());
        q.opt("sqft_min", params.sqft_min.as_ref());
        q.opt("sqft_max", params.sqft_max.as_ref());
        q.opt("lot_min", params.lot_min.as_ref());
        q.opt("lot_max", params.lot_max.as_ref());
        q.opt("year_built_min", params.year_built_min.as_ref());
        q.opt("year_built_max", params.year_built_max.as_ref());
        q.opt("max_days_on_market", params.max_days_on_market.as_ref());
        q.opt("north", params.north.as_ref());
        q.opt("south", params.south.as_ref());
        q.opt("east", params.east.as_ref());
        q.opt("west", params.west.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }
}

// ===== Models =====

/// Parameters for [`GetAgentParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetAgentParams {
    /// Full Redfin /realestateagents/ URL
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Redfin agent id
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_id: Option<String>,
}

/// Parameters for [`AutocompleteParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct AutocompleteParams {
    /// Partial location — city, ZIP, address, neighborhood
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
}

/// Parameters for [`ListMarketsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ListMarketsParams {}

/// Parameters for [`GetPropertyByUrlParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetPropertyByUrlParams {
    /// Full Redfin property URL (/CA/City/.../home/12345678)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

/// Parameters for [`GetPropertyParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetPropertyParams {}

/// Parameters for [`SearchParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct SearchParams {
    /// City/state, ZIP, address or neighborhood
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
    /// relevant|newest|price_high_to_low|price_low_to_high|square_feet|lot_size|price_per_sqft|beds|baths
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sort: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub price_min: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub price_max: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub beds_min: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub baths_min: Option<f64>,
    /// house|condo|townhouse|multi_family|land|mobile|coop|other
    #[serde(skip_serializing_if = "Option::is_none")]
    pub home_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sqft_min: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sqft_max: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lot_min: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lot_max: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub year_built_min: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub year_built_max: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_days_on_market: Option<i64>,
    /// Map bounds for tiling past the cap
    #[serde(skip_serializing_if = "Option::is_none")]
    pub north: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub south: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub east: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub west: Option<f64>,
}
