// @generated by `cargo run -p xtask -- gen` from specs/immobiliare.json — do not edit by hand.
#![allow(clippy::all)]
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    non_snake_case,
    rustdoc::all
)]

use crate::core::{Client, Error, Method, QueryParams, Result};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;

/// Handle for the `immobiliare` platform. Obtain via [`crate::ScrapeBadger::immobiliare`].
#[derive(Clone)]
pub struct Immobiliare {
    client: Client,
}

impl Immobiliare {
    pub(crate) fn new(client: Client) -> Self {
        Self { client }
    }

    /// Access the underlying transport client.
    pub fn client(&self) -> &Client {
        &self.client
    }

    /// Get agency profile
    ///
    /// Public agency/advertiser profile.
    /// `GET /v1/immobiliare/agencies/{agency_id}`
    pub async fn get_agency(
        &self,
        agency_id: impl AsRef<str>,
        params: GetAgencyParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/immobiliare/agencies/{agency_id}",
            agency_id = agency_id.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("market", params.market.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get an agency's listings
    ///
    /// An agency's active listings.
    /// `GET /v1/immobiliare/agencies/{agency_id}/listings`
    pub async fn get_agency_listings(
        &self,
        agency_id: impl AsRef<str>,
        params: GetAgencyListingsParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/immobiliare/agencies/{agency_id}/listings",
            agency_id = agency_id.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("market", params.market.as_ref());
        q.opt("contract", params.contract.as_ref());
        q.opt("page", params.page.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Location autocomplete
    ///
    /// Resolve a place name to region/province/city ids usable in search.
    /// `GET /v1/immobiliare/autocomplete`
    pub async fn autocomplete(&self, params: AutocompleteParams) -> Result<Value> {
        let path = "/v1/immobiliare/autocomplete".to_string();
        let mut q = QueryParams::new();
        q.opt("query", params.query.as_ref());
        q.opt("market", params.market.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get listing detail
    ///
    /// Full detail for a single listing.
    /// `GET /v1/immobiliare/listings/{listing_id}`
    pub async fn get_listing(
        &self,
        listing_id: impl AsRef<str>,
        params: GetListingParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/immobiliare/listings/{listing_id}",
            listing_id = listing_id.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("market", params.market.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Price €/m² time series
    ///
    /// Historical €/m² price statistics for an area.
    /// `GET /v1/immobiliare/market-insights/prices`
    pub async fn price_stats(&self, params: PriceStatsParams) -> Result<Value> {
        let path = "/v1/immobiliare/market-insights/prices".to_string();
        let mut q = QueryParams::new();
        q.opt("market", params.market.as_ref());
        q.opt("region_id", params.region_id.as_ref());
        q.opt("province_id", params.province_id.as_ref());
        q.opt("city_id", params.city_id.as_ref());
        q.opt("contract", params.contract.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// List markets
    /// `GET /v1/immobiliare/markets`
    pub async fn list_markets(&self, params: ListMarketsParams) -> Result<Value> {
        let path = "/v1/immobiliare/markets".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// List filter enums
    /// `GET /v1/immobiliare/reference`
    pub async fn reference(&self, params: ReferenceParams) -> Result<Value> {
        let path = "/v1/immobiliare/reference".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Search listings
    ///
    /// Search Immobiliare-group listings (scope by location + contract + filters).
    /// `GET /v1/immobiliare/search`
    pub async fn search(&self, params: SearchParams) -> Result<Value> {
        let path = "/v1/immobiliare/search".to_string();
        let mut q = QueryParams::new();
        q.opt("market", params.market.as_ref());
        q.opt("location", params.location.as_ref());
        q.opt("region_id", params.region_id.as_ref());
        q.opt("province_id", params.province_id.as_ref());
        q.opt("city_id", params.city_id.as_ref());
        q.opt("contract", params.contract.as_ref());
        q.opt("category", params.category.as_ref());
        q.opt("price_min", params.price_min.as_ref());
        q.opt("price_max", params.price_max.as_ref());
        q.opt("surface_min", params.surface_min.as_ref());
        q.opt("surface_max", params.surface_max.as_ref());
        q.opt("rooms_min", params.rooms_min.as_ref());
        q.opt("rooms_max", params.rooms_max.as_ref());
        q.opt("bathrooms_min", params.bathrooms_min.as_ref());
        q.opt("sort", params.sort.as_ref());
        q.opt("page", params.page.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }
}

// ===== Models =====

/// Parameters for [`GetAgencyParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetAgencyParams {
    /// it | es | gr | lu
    #[serde(skip_serializing_if = "Option::is_none")]
    pub market: Option<String>,
}

/// Parameters for [`GetAgencyListingsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetAgencyListingsParams {
    /// it | es | gr | lu
    #[serde(skip_serializing_if = "Option::is_none")]
    pub market: Option<String>,
    /// sale | rent
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contract: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
}

/// Parameters for [`AutocompleteParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct AutocompleteParams {
    /// Free-text place name, e.g. 'Milano'
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    /// it | es | gr | lu
    #[serde(skip_serializing_if = "Option::is_none")]
    pub market: Option<String>,
}

/// Parameters for [`GetListingParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetListingParams {
    /// it | es | gr | lu
    #[serde(skip_serializing_if = "Option::is_none")]
    pub market: Option<String>,
}

/// Parameters for [`PriceStatsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct PriceStatsParams {
    /// it | es | gr | lu
    #[serde(skip_serializing_if = "Option::is_none")]
    pub market: Option<String>,
    /// Region id, e.g. 'lom'
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region_id: Option<String>,
    /// Province id, e.g. 'MI'
    #[serde(skip_serializing_if = "Option::is_none")]
    pub province_id: Option<String>,
    /// City id (idComune)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub city_id: Option<String>,
    /// sale | rent
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contract: Option<String>,
}

/// Parameters for [`ListMarketsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ListMarketsParams {}

/// Parameters for [`ReferenceParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ReferenceParams {}

/// Parameters for [`SearchParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct SearchParams {
    /// it | es | gr | lu
    #[serde(skip_serializing_if = "Option::is_none")]
    pub market: Option<String>,
    /// Free-text place (auto-resolved)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    /// fkRegione (from /autocomplete)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region_id: Option<String>,
    /// idProvincia (from /autocomplete)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub province_id: Option<String>,
    /// idComune (from /autocomplete)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub city_id: Option<String>,
    /// sale | rent
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contract: Option<String>,
    /// see /reference
    #[serde(skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub price_min: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub price_max: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub surface_min: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub surface_max: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rooms_min: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rooms_max: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bathrooms_min: Option<i64>,
    /// see /reference
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sort: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
}
