// @generated by `cargo run -p xtask -- gen` from specs/zillow.json — do not edit by hand.
#![allow(clippy::all)]
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    non_snake_case,
    rustdoc::all
)]

use crate::core::{Client, Error, Method, QueryParams, Result};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;

/// Handle for the `zillow` platform. Obtain via [`crate::ScrapeBadger::zillow`].
#[derive(Clone)]
pub struct Zillow {
    client: Client,
}

impl Zillow {
    pub(crate) fn new(client: Client) -> Self {
        Self { client }
    }

    /// Access the underlying transport client.
    pub fn client(&self) -> &Client {
        &self.client
    }

    /// Get agent profile + listings
    ///
    /// Get a Zillow professional's profile and their active listings.
    /// `GET /v1/zillow/agent`
    pub async fn get_agent(&self, params: GetAgentParams) -> Result<Value> {
        let path = "/v1/zillow/agent".to_string();
        let mut q = QueryParams::new();
        q.opt("username", params.username.as_ref());
        q.opt("url", params.url.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Region/address suggestions
    ///
    /// Resolve a search term to Zillow regions/addresses.
    /// `GET /v1/zillow/autocomplete`
    pub async fn autocomplete(&self, params: AutocompleteParams) -> Result<Value> {
        let path = "/v1/zillow/autocomplete".to_string();
        let mut q = QueryParams::new();
        q.opt("query", params.query.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// List coverage markets
    ///
    /// List Zillow coverage regions (US + Canada).
    /// `GET /v1/zillow/markets`
    pub async fn list_markets(&self, params: ListMarketsParams) -> Result<Value> {
        let path = "/v1/zillow/markets".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get property detail by URL
    ///
    /// Get a single Zillow property's full detail by its homedetails URL.
    /// `GET /v1/zillow/property`
    pub async fn get_property_by_url(&self, params: GetPropertyByUrlParams) -> Result<Value> {
        let path = "/v1/zillow/property".to_string();
        let mut q = QueryParams::new();
        q.opt("url", params.url.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get property detail
    ///
    /// Get a single Zillow property's full detail by zpid.
    /// `GET /v1/zillow/property/{zpid}`
    pub async fn get_property(
        &self,
        zpid: impl AsRef<str>,
        params: GetPropertyParams,
    ) -> Result<Value> {
        let path = format!("/v1/zillow/property/{zpid}", zpid = zpid.as_ref());
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Search properties
    ///
    /// Search Zillow for for-sale / for-rent / recently-sold properties.
    /// `GET /v1/zillow/search`
    pub async fn search(&self, params: SearchParams) -> Result<Value> {
        let path = "/v1/zillow/search".to_string();
        let mut q = QueryParams::new();
        q.opt("location", params.location.as_ref());
        q.opt("status", params.status.as_ref());
        q.opt("page", params.page.as_ref());
        q.opt("sort", params.sort.as_ref());
        q.opt("price_min", params.price_min.as_ref());
        q.opt("price_max", params.price_max.as_ref());
        q.opt("beds_min", params.beds_min.as_ref());
        q.opt("baths_min", params.baths_min.as_ref());
        q.opt("home_type", params.home_type.as_ref());
        q.opt("sqft_min", params.sqft_min.as_ref());
        q.opt("sqft_max", params.sqft_max.as_ref());
        q.opt("lot_min", params.lot_min.as_ref());
        q.opt("lot_max", params.lot_max.as_ref());
        q.opt("year_built_min", params.year_built_min.as_ref());
        q.opt("year_built_max", params.year_built_max.as_ref());
        q.opt("hoa_max", params.hoa_max.as_ref());
        q.opt("keywords", params.keywords.as_ref());
        q.opt("days_on", params.days_on.as_ref());
        q.opt("north", params.north.as_ref());
        q.opt("south", params.south.as_ref());
        q.opt("east", params.east.as_ref());
        q.opt("west", params.west.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }
}

// ===== Models =====

/// Parameters for [`GetAgentParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetAgentParams {
    /// Zillow profile username
    #[serde(skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    /// Full Zillow /profile/... URL
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

/// Parameters for [`AutocompleteParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct AutocompleteParams {
    /// Partial location — city, ZIP, address, neighborhood
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
}

/// Parameters for [`ListMarketsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ListMarketsParams {}

/// Parameters for [`GetPropertyByUrlParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetPropertyByUrlParams {
    /// Full Zillow /homedetails/... URL
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

/// Parameters for [`GetPropertyParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetPropertyParams {}

/// Parameters for [`SearchParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct SearchParams {
    /// City/state, ZIP, address or neighborhood
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    /// for_sale|for_rent|sold
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
    /// homes_for_you|newest|price_high_to_low|price_low_to_high|bedrooms|bathrooms|square_feet|lot_size|year_built
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sort: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub price_min: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub price_max: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub beds_min: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub baths_min: Option<f64>,
    /// houses|condos|townhomes|apartments|manufactured|lots|multi_family
    #[serde(skip_serializing_if = "Option::is_none")]
    pub home_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sqft_min: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sqft_max: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lot_min: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lot_max: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub year_built_min: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub year_built_max: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hoa_max: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub keywords: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub days_on: Option<String>,
    /// Map bounds for tiling past the 820 cap
    #[serde(skip_serializing_if = "Option::is_none")]
    pub north: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub south: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub east: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub west: Option<f64>,
}
