// @generated by `cargo run -p xtask -- gen` from specs/leboncoin.json — do not edit by hand.
#![allow(clippy::all)]
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    non_snake_case,
    rustdoc::all
)]

use crate::core::{Client, Error, Method, QueryParams, Result};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;

/// Handle for the `leboncoin` platform. Obtain via [`crate::ScrapeBadger::leboncoin`].
#[derive(Clone)]
pub struct Leboncoin {
    client: Client,
}

impl Leboncoin {
    pub(crate) fn new(client: Client) -> Self {
        Self { client }
    }

    /// Access the underlying transport client.
    pub fn client(&self) -> &Client {
        &self.client
    }

    /// Get ad detail
    ///
    /// Full detail for a Leboncoin ad.
    /// `GET /v1/leboncoin/ads/{list_id}`
    pub async fn get_ad(&self, list_id: impl AsRef<str>, params: GetAdParams) -> Result<Value> {
        let path = format!("/v1/leboncoin/ads/{list_id}", list_id = list_id.as_ref());
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get similar ads
    ///
    /// Ads Leboncoin surfaces as similar to the given ad.
    /// `GET /v1/leboncoin/ads/{list_id}/similar`
    pub async fn get_similar(
        &self,
        list_id: impl AsRef<str>,
        params: GetSimilarParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/leboncoin/ads/{list_id}/similar",
            list_id = list_id.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("limit", params.limit.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// List categories
    /// `GET /v1/leboncoin/categories`
    pub async fn list_categories(&self, params: ListCategoriesParams) -> Result<Value> {
        let path = "/v1/leboncoin/categories".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// List departments
    /// `GET /v1/leboncoin/departments`
    pub async fn list_departments(&self, params: ListDepartmentsParams) -> Result<Value> {
        let path = "/v1/leboncoin/departments".to_string();
        let mut q = QueryParams::new();
        q.opt("region_id", params.region_id.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Location autocomplete
    /// `GET /v1/leboncoin/locations/search`
    pub async fn search_locations(&self, params: SearchLocationsParams) -> Result<Value> {
        let path = "/v1/leboncoin/locations/search".to_string();
        let mut q = QueryParams::new();
        q.opt("q", params.q.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// List markets
    /// `GET /v1/leboncoin/markets`
    pub async fn list_markets(&self, params: ListMarketsParams) -> Result<Value> {
        let path = "/v1/leboncoin/markets".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// List regions
    /// `GET /v1/leboncoin/regions`
    pub async fn list_regions(&self, params: ListRegionsParams) -> Result<Value> {
        let path = "/v1/leboncoin/regions".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Search Leboncoin ads
    ///
    /// Search Leboncoin classifieds (France; scope by region/department/city).
    /// `GET /v1/leboncoin/search`
    pub async fn search_ads(&self, params: SearchAdsParams) -> Result<Value> {
        let path = "/v1/leboncoin/search".to_string();
        let mut q = QueryParams::new();
        q.opt("text", params.text.as_ref());
        q.opt("category", params.category.as_ref());
        q.opt("region_id", params.region_id.as_ref());
        q.opt("department_id", params.department_id.as_ref());
        q.opt("city", params.city.as_ref());
        q.opt("zipcode", params.zipcode.as_ref());
        q.opt("price_min", params.price_min.as_ref());
        q.opt("price_max", params.price_max.as_ref());
        q.opt("owner_type", params.owner_type.as_ref());
        q.opt("ad_type", params.ad_type.as_ref());
        q.opt("sort", params.sort.as_ref());
        q.opt("page", params.page.as_ref());
        q.opt("limit", params.limit.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get seller profile
    ///
    /// Public seller/pro-store profile.
    /// `GET /v1/leboncoin/sellers/{user_id}`
    pub async fn get_seller(
        &self,
        user_id: impl AsRef<str>,
        params: GetSellerParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/leboncoin/sellers/{user_id}",
            user_id = user_id.as_ref()
        );
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get a seller's ads
    ///
    /// A seller's active ads.
    /// `GET /v1/leboncoin/sellers/{user_id}/listings`
    pub async fn get_seller_listings(
        &self,
        user_id: impl AsRef<str>,
        params: GetSellerListingsParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/leboncoin/sellers/{user_id}/listings",
            user_id = user_id.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("page", params.page.as_ref());
        q.opt("limit", params.limit.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }
}

// ===== Models =====

/// Parameters for [`GetAdParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetAdParams {}

/// Parameters for [`GetSimilarParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetSimilarParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
}

/// Parameters for [`ListCategoriesParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ListCategoriesParams {}

/// Parameters for [`ListDepartmentsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ListDepartmentsParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region_id: Option<String>,
}

/// Parameters for [`SearchLocationsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct SearchLocationsParams {
    /// Place name
    #[serde(skip_serializing_if = "Option::is_none")]
    pub q: Option<String>,
}

/// Parameters for [`ListMarketsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ListMarketsParams {}

/// Parameters for [`ListRegionsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ListRegionsParams {}

/// Parameters for [`SearchAdsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct SearchAdsParams {
    /// Free-text query
    #[serde(skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    /// Category id (see /categories)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    /// Region id (see /regions)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region_id: Option<String>,
    /// Department id, e.g. 75
    #[serde(skip_serializing_if = "Option::is_none")]
    pub department_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub zipcode: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub price_min: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub price_max: Option<i64>,
    /// all | pro | private
    #[serde(skip_serializing_if = "Option::is_none")]
    pub owner_type: Option<String>,
    /// offer | demand
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ad_type: Option<String>,
    /// relevance|newest|oldest|price_low|price_high
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sort: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
}

/// Parameters for [`GetSellerParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetSellerParams {}

/// Parameters for [`GetSellerListingsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetSellerListingsParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
}
