// @generated by `cargo run -p xtask -- gen` from specs/realtor.json — do not edit by hand.
#![allow(clippy::all)]
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    non_snake_case,
    rustdoc::all
)]

use crate::core::{Client, Error, Method, QueryParams, Result};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;

/// Handle for the `realtor` platform. Obtain via [`crate::ScrapeBadger::realtor`].
#[derive(Clone)]
pub struct Realtor {
    client: Client,
}

impl Realtor {
    pub(crate) fn new(client: Client) -> Self {
        Self { client }
    }

    /// Access the underlying transport client.
    pub fn client(&self) -> &Client {
        &self.client
    }

    /// Location autocomplete
    ///
    /// Resolve a location query into candidate places to feed /search.
    /// `GET /v1/realtor/autocomplete`
    pub async fn autocomplete(&self, params: AutocompleteParams) -> Result<Value> {
        let path = "/v1/realtor/autocomplete".to_string();
        let mut q = QueryParams::new();
        q.opt("query", params.query.as_ref());
        q.opt("market", params.market.as_ref());
        q.opt("limit", params.limit.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// List markets
    ///
    /// List supported Realtor markets (US = realtor.com, CA = realtor.ca).
    /// `GET /v1/realtor/markets`
    pub async fn list_markets(&self, params: ListMarketsParams) -> Result<Value> {
        let path = "/v1/realtor/markets".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get full property detail
    ///
    /// Full listing detail: features, tax & price history, schools, photos, agents.
    /// `GET /v1/realtor/properties/{property_id}`
    pub async fn get_property(
        &self,
        property_id: impl AsRef<str>,
        params: GetPropertyParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/realtor/properties/{property_id}",
            property_id = property_id.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("market", params.market.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Search property listings
    ///
    /// Search for-sale/for-rent/sold listings with rich filters.
    /// `GET /v1/realtor/search`
    pub async fn search(&self, params: SearchParams) -> Result<Value> {
        let path = "/v1/realtor/search".to_string();
        let mut q = QueryParams::new();
        q.opt("location", params.location.as_ref());
        q.opt("market", params.market.as_ref());
        q.opt("status", params.status.as_ref());
        q.opt("price_min", params.price_min.as_ref());
        q.opt("price_max", params.price_max.as_ref());
        q.opt("beds_min", params.beds_min.as_ref());
        q.opt("baths_min", params.baths_min.as_ref());
        q.opt("sqft_min", params.sqft_min.as_ref());
        q.opt("sqft_max", params.sqft_max.as_ref());
        q.opt("property_type", params.property_type.as_ref());
        q.opt("sort", params.sort.as_ref());
        q.opt("page", params.page.as_ref());
        q.opt("limit", params.limit.as_ref());
        q.opt("lat_min", params.lat_min.as_ref());
        q.opt("lat_max", params.lat_max.as_ref());
        q.opt("lng_min", params.lng_min.as_ref());
        q.opt("lng_max", params.lng_max.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }
}

// ===== Models =====

/// Parameters for [`AutocompleteParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct AutocompleteParams {
    /// Freetext location (city, ZIP/postal, address…)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    /// us (realtor.com) | ca (realtor.ca)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub market: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
}

/// Parameters for [`ListMarketsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ListMarketsParams {}

/// Parameters for [`GetPropertyParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetPropertyParams {
    /// us (realtor.com) | ca (realtor.ca)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub market: Option<String>,
}

/// Parameters for [`SearchParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct SearchParams {
    /// 'Austin, TX', a ZIP, 'Toronto, ON'…
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    /// us (realtor.com) | ca (realtor.ca)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub market: Option<String>,
    /// for_sale | for_rent | sold | pending
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub price_min: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub price_max: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub beds_min: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub baths_min: Option<i64>,
    /// US only
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sqft_min: Option<i64>,
    /// US only
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sqft_max: Option<i64>,
    /// US only, CSV of property types
    #[serde(skip_serializing_if = "Option::is_none")]
    pub property_type: Option<String>,
    /// relevant | newest | price_low | price_high | photo_count
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sort: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    /// CA bbox south
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lat_min: Option<f64>,
    /// CA bbox north
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lat_max: Option<f64>,
    /// CA bbox west
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lng_min: Option<f64>,
    /// CA bbox east
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lng_max: Option<f64>,
}
