// @generated by `cargo run -p xtask -- gen` from specs/linkedin.json — do not edit by hand.
#![allow(clippy::all)]
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    non_snake_case,
    rustdoc::all
)]

use crate::core::{Client, Error, Method, QueryParams, Result};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;

/// Handle for the `linkedin` platform. Obtain via [`crate::ScrapeBadger::linkedin`].
#[derive(Clone)]
pub struct Linkedin {
    client: Client,
}

impl Linkedin {
    pub(crate) fn new(client: Client) -> Self {
        Self { client }
    }

    /// Access the underlying transport client.
    pub fn client(&self) -> &Client {
        &self.client
    }

    /// Get a public article
    ///
    /// A public Pulse article — title, body, author, reactions (JSON-LD).
    /// `GET /v1/linkedin/articles/{article_slug}`
    pub async fn get_article(
        &self,
        article_slug: impl AsRef<str>,
        params: GetArticleParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/linkedin/articles/{article_slug}",
            article_slug = article_slug.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("country", params.country.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get a company's job postings
    ///
    /// Public job postings for a company (numeric company id from the company endpoint).
    /// `GET /v1/linkedin/companies/{company_id}/jobs`
    pub async fn company_jobs(
        &self,
        company_id: impl AsRef<str>,
        params: CompanyJobsParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/linkedin/companies/{company_id}/jobs",
            company_id = company_id.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("start", params.start.as_ref());
        q.opt("country", params.country.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get company
    ///
    /// Public company page — industry, size, HQ, followers, specialties (JSON-LD + SSR).
    /// `GET /v1/linkedin/companies/{universal_name}`
    pub async fn get_company(
        &self,
        universal_name: impl AsRef<str>,
        params: GetCompanyParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/linkedin/companies/{universal_name}",
            universal_name = universal_name.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("country", params.country.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Suggest location geo ids
    ///
    /// Resolve a name to LinkedIn ids (job-search ``geo_id`` / ``company_id`` helper).
    /// `GET /v1/linkedin/geo/suggest`
    pub async fn geo_suggest(&self, params: GeoSuggestParams) -> Result<Value> {
        let path = "/v1/linkedin/geo/suggest".to_string();
        let mut q = QueryParams::new();
        q.opt("query", params.query.as_ref());
        q.opt("type", params.type_.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Search LinkedIn jobs
    ///
    /// Search public LinkedIn job postings (guest API, no login).
    /// `GET /v1/linkedin/jobs/search`
    pub async fn jobs_search(&self, params: JobsSearchParams) -> Result<Value> {
        let path = "/v1/linkedin/jobs/search".to_string();
        let mut q = QueryParams::new();
        q.opt("keywords", params.keywords.as_ref());
        q.opt("location", params.location.as_ref());
        q.opt("geo_id", params.geo_id.as_ref());
        q.opt("company_id", params.company_id.as_ref());
        q.opt("date_posted", params.date_posted.as_ref());
        q.opt("experience", params.experience.as_ref());
        q.opt("job_type", params.job_type.as_ref());
        q.opt("workplace", params.workplace.as_ref());
        q.opt("sort", params.sort.as_ref());
        q.opt("start", params.start.as_ref());
        q.opt("country", params.country.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get job detail
    ///
    /// Full detail for one job posting (guest API, no login).
    /// `GET /v1/linkedin/jobs/{job_id}`
    pub async fn get_job(&self, job_id: impl AsRef<str>, params: GetJobParams) -> Result<Value> {
        let path = format!("/v1/linkedin/jobs/{job_id}", job_id = job_id.as_ref());
        let mut q = QueryParams::new();
        q.opt("country", params.country.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get a course
    ///
    /// A public LinkedIn Learning course — provider, workload, instructors, rating.
    /// `GET /v1/linkedin/learning/{course_slug}`
    pub async fn get_course(
        &self,
        course_slug: impl AsRef<str>,
        params: GetCourseParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/linkedin/learning/{course_slug}",
            course_slug = course_slug.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("country", params.country.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get a public post
    ///
    /// A public activity share — text, author, reactions, comments (JSON-LD).
    /// `GET /v1/linkedin/posts/{post_slug}`
    pub async fn get_post(
        &self,
        post_slug: impl AsRef<str>,
        params: GetPostParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/linkedin/posts/{post_slug}",
            post_slug = post_slug.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("country", params.country.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get public profile
    ///
    /// Public profile by vanity id (the ``/in/{public_id}`` slug) — name, headline,
    /// location, about, experience, education (public JSON-LD + SSR subset).
    /// `GET /v1/linkedin/profiles/{public_id}`
    pub async fn get_profile(
        &self,
        public_id: impl AsRef<str>,
        params: GetProfileParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/linkedin/profiles/{public_id}",
            public_id = public_id.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("country", params.country.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get school
    ///
    /// Public school page — name, description, website, follower/alumni counts.
    /// `GET /v1/linkedin/schools/{universal_name}`
    pub async fn get_school(
        &self,
        universal_name: impl AsRef<str>,
        params: GetSchoolParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/linkedin/schools/{universal_name}",
            universal_name = universal_name.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("country", params.country.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }
}

// ===== Models =====

/// Parameters for [`GetArticleParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetArticleParams {
    /// Residential proxy country
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
}

/// Parameters for [`CompanyJobsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct CompanyJobsParams {
    /// Pagination offset (0, 25, 50, ...)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub start: Option<i64>,
    /// Residential proxy country
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
}

/// Parameters for [`GetCompanyParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetCompanyParams {
    /// Residential proxy country
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
}

/// Parameters for [`GeoSuggestParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GeoSuggestParams {
    /// Location text, e.g. 'London'
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    /// geo | company
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "type")]
    pub type_: Option<String>,
}

/// Parameters for [`JobsSearchParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct JobsSearchParams {
    /// Job title / keywords
    #[serde(skip_serializing_if = "Option::is_none")]
    pub keywords: Option<String>,
    /// Location text, e.g. 'New York'
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    /// LinkedIn numeric geo id (overrides location)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub geo_id: Option<String>,
    /// Restrict to a company (numeric id)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub company_id: Option<String>,
    /// past_24h | past_week | past_month | any
    #[serde(skip_serializing_if = "Option::is_none")]
    pub date_posted: Option<String>,
    /// internship|entry|associate|mid_senior|director|executive (comma-separated)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub experience: Option<String>,
    /// full_time|part_time|contract|temporary|internship|volunteer|other
    #[serde(skip_serializing_if = "Option::is_none")]
    pub job_type: Option<String>,
    /// onsite|remote|hybrid (comma-separated)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub workplace: Option<String>,
    /// relevant | recent
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sort: Option<String>,
    /// Pagination offset (0, 25, 50, ...)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub start: Option<i64>,
    /// Residential proxy country
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
}

/// Parameters for [`GetJobParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetJobParams {
    /// Residential proxy country
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
}

/// Parameters for [`GetCourseParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetCourseParams {
    /// Residential proxy country
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
}

/// Parameters for [`GetPostParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetPostParams {
    /// Residential proxy country
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
}

/// Parameters for [`GetProfileParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetProfileParams {
    /// Residential proxy country
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
}

/// Parameters for [`GetSchoolParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetSchoolParams {
    /// Residential proxy country
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
}
