// @generated by `cargo run -p xtask -- gen` from specs/idealista.json — do not edit by hand.
#![allow(clippy::all)]
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    non_snake_case,
    rustdoc::all
)]

use crate::core::{Client, Error, Method, QueryParams, Result};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;

/// Handle for the `idealista` platform. Obtain via [`crate::ScrapeBadger::idealista`].
#[derive(Clone)]
pub struct Idealista {
    client: Client,
}

impl Idealista {
    pub(crate) fn new(client: Client) -> Self {
        Self { client }
    }

    /// Access the underlying transport client.
    pub fn client(&self) -> &Client {
        &self.client
    }

    /// Agency by phone
    ///
    /// Reverse-lookup the agency behind a contact phone (national number), with its listings.
    /// `GET /v1/idealista/agency/by-phone/{phone}`
    pub async fn agency_by_phone(
        &self,
        phone: impl AsRef<str>,
        params: AgencyByPhoneParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/idealista/agency/by-phone/{phone}",
            phone = phone.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("market", params.market.as_ref());
        q.opt("operation", params.operation.as_ref());
        q.opt("property_type", params.property_type.as_ref());
        q.opt("page", params.page.as_ref());
        q.opt("max_items", params.max_items.as_ref());
        q.opt("include_listings", params.include_listings.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Agency profile + listings
    ///
    /// An agency's microsite profile plus a page of its listings (by URL-slug shortName).
    /// `GET /v1/idealista/agency/{short_name}`
    pub async fn agency(&self, short_name: impl AsRef<str>, params: AgencyParams) -> Result<Value> {
        let path = format!(
            "/v1/idealista/agency/{short_name}",
            short_name = short_name.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("market", params.market.as_ref());
        q.opt("operation", params.operation.as_ref());
        q.opt("property_type", params.property_type.as_ref());
        q.opt("page", params.page.as_ref());
        q.opt("max_items", params.max_items.as_ref());
        q.opt("include_listings", params.include_listings.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// List markets
    ///
    /// List supported Idealista markets (ES, IT, PT).
    /// `GET /v1/idealista/markets`
    pub async fn list_markets(&self, params: ListMarketsParams) -> Result<Value> {
        let path = "/v1/idealista/markets".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get property detail
    ///
    /// Get a single Idealista listing's full detail (energy cert, characteristics, media).
    /// `GET /v1/idealista/properties/{property_code}`
    pub async fn property_detail(
        &self,
        property_code: impl AsRef<str>,
        params: PropertyDetailParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/idealista/properties/{property_code}",
            property_code = property_code.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("market", params.market.as_ref());
        q.opt("locale", params.locale.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get listing engagement stats
    ///
    /// Engagement counters for a listing: views, email contacts, sent-to-friend, favourites.
    /// `GET /v1/idealista/properties/{property_code}/stats`
    pub async fn property_stats(
        &self,
        property_code: impl AsRef<str>,
        params: PropertyStatsParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/idealista/properties/{property_code}/stats",
            property_code = property_code.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("market", params.market.as_ref());
        q.opt("locale", params.locale.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Search listings
    ///
    /// Search Idealista real-estate listings by location code.
    /// `GET /v1/idealista/search`
    pub async fn search(&self, params: SearchParams) -> Result<Value> {
        let path = "/v1/idealista/search".to_string();
        let mut q = QueryParams::new();
        q.opt("location", params.location.as_ref());
        q.opt("operation", params.operation.as_ref());
        q.opt("property_type", params.property_type.as_ref());
        q.opt("market", params.market.as_ref());
        q.opt("page", params.page.as_ref());
        q.opt("max_items", params.max_items.as_ref());
        q.opt("sort_by", params.sort_by.as_ref());
        q.opt("sort_order", params.sort_order.as_ref());
        q.opt("min_price", params.min_price.as_ref());
        q.opt("max_price", params.max_price.as_ref());
        q.opt("min_size", params.min_size.as_ref());
        q.opt("max_size", params.max_size.as_ref());
        q.opt("min_rooms", params.min_rooms.as_ref());
        q.opt("max_rooms", params.max_rooms.as_ref());
        q.opt("locale", params.locale.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Search all (beats result cap)
    ///
    /// Full inventory for a location, beating Idealista's ~1800 per-search cap via
    /// price-range tiling (deduped). Billed per page fetched.
    /// `GET /v1/idealista/search/all`
    pub async fn search_all(&self, params: SearchAllParams) -> Result<Value> {
        let path = "/v1/idealista/search/all".to_string();
        let mut q = QueryParams::new();
        q.opt("location", params.location.as_ref());
        q.opt("operation", params.operation.as_ref());
        q.opt("property_type", params.property_type.as_ref());
        q.opt("market", params.market.as_ref());
        q.opt("max_results", params.max_results.as_ref());
        q.opt("min_price", params.min_price.as_ref());
        q.opt("max_price", params.max_price.as_ref());
        q.opt("min_size", params.min_size.as_ref());
        q.opt("max_size", params.max_size.as_ref());
        q.opt("min_rooms", params.min_rooms.as_ref());
        q.opt("max_rooms", params.max_rooms.as_ref());
        q.opt("locale", params.locale.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Resolve locations
    ///
    /// Resolve a free-text query into Idealista location codes for a search.
    /// `GET /v1/idealista/suggest`
    pub async fn suggest(&self, params: SuggestParams) -> Result<Value> {
        let path = "/v1/idealista/suggest".to_string();
        let mut q = QueryParams::new();
        q.opt("query", params.query.as_ref());
        q.opt("operation", params.operation.as_ref());
        q.opt("property_type", params.property_type.as_ref());
        q.opt("market", params.market.as_ref());
        q.opt("locale", params.locale.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }
}

// ===== Models =====

/// Parameters for [`AgencyByPhoneParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct AgencyByPhoneParams {
    /// es|it|pt
    #[serde(skip_serializing_if = "Option::is_none")]
    pub market: Option<String>,
    /// sale|rent
    #[serde(skip_serializing_if = "Option::is_none")]
    pub operation: Option<String>,
    /// homes|offices|premises|garages|newDevelopments|lands|storageRooms|buildings|bedrooms
    #[serde(skip_serializing_if = "Option::is_none")]
    pub property_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_items: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub include_listings: Option<bool>,
}

/// Parameters for [`AgencyParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct AgencyParams {
    /// es|it|pt
    #[serde(skip_serializing_if = "Option::is_none")]
    pub market: Option<String>,
    /// sale|rent
    #[serde(skip_serializing_if = "Option::is_none")]
    pub operation: Option<String>,
    /// homes|offices|premises|garages|newDevelopments|lands|storageRooms|buildings|bedrooms
    #[serde(skip_serializing_if = "Option::is_none")]
    pub property_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_items: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub include_listings: Option<bool>,
}

/// Parameters for [`ListMarketsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ListMarketsParams {}

/// Parameters for [`PropertyDetailParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct PropertyDetailParams {
    /// es|it|pt
    #[serde(skip_serializing_if = "Option::is_none")]
    pub market: Option<String>,
    /// Response language (en, es, it, pt)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub locale: Option<String>,
}

/// Parameters for [`PropertyStatsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct PropertyStatsParams {
    /// es|it|pt
    #[serde(skip_serializing_if = "Option::is_none")]
    pub market: Option<String>,
    /// Language for stat labels
    #[serde(skip_serializing_if = "Option::is_none")]
    pub locale: Option<String>,
}

/// Parameters for [`SearchParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct SearchParams {
    /// Idealista location code (from /suggest)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    /// sale|rent
    #[serde(skip_serializing_if = "Option::is_none")]
    pub operation: Option<String>,
    /// homes|offices|premises|garages|newDevelopments|lands|storageRooms|buildings|bedrooms
    #[serde(skip_serializing_if = "Option::is_none")]
    pub property_type: Option<String>,
    /// es|it|pt
    #[serde(skip_serializing_if = "Option::is_none")]
    pub market: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_items: Option<i64>,
    /// distance|size|rooms|floor|ratioeurm2|price|street|photos|modificationDate|publicationDate|weigh|priceDown|preservationTypeAndPrice|privateAds
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sort_by: Option<String>,
    /// asc|desc
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sort_order: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_price: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_price: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_size: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_size: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_rooms: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_rooms: Option<i64>,
    /// Response language (en, es, it, pt)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub locale: Option<String>,
}

/// Parameters for [`SearchAllParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct SearchAllParams {
    /// Idealista location code (from /suggest)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    /// sale|rent
    #[serde(skip_serializing_if = "Option::is_none")]
    pub operation: Option<String>,
    /// homes|offices|premises|garages|newDevelopments|lands|storageRooms|buildings|bedrooms
    #[serde(skip_serializing_if = "Option::is_none")]
    pub property_type: Option<String>,
    /// es|it|pt
    #[serde(skip_serializing_if = "Option::is_none")]
    pub market: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_results: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_price: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_price: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_size: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_size: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_rooms: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_rooms: Option<i64>,
    /// Response language (en, es, it, pt)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub locale: Option<String>,
}

/// Parameters for [`SuggestParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct SuggestParams {
    /// Free-text location, e.g. 'sagrada familia'
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    /// sale|rent
    #[serde(skip_serializing_if = "Option::is_none")]
    pub operation: Option<String>,
    /// homes|offices|premises|garages|newDevelopments|lands|storageRooms|buildings|bedrooms
    #[serde(skip_serializing_if = "Option::is_none")]
    pub property_type: Option<String>,
    /// es|it|pt
    #[serde(skip_serializing_if = "Option::is_none")]
    pub market: Option<String>,
    /// Response language (en, es, it, pt)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub locale: Option<String>,
}
