// @generated by `cargo run -p xtask -- gen` from specs/amazon.json — do not edit by hand.
#![allow(clippy::all)]
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    non_snake_case,
    rustdoc::all
)]

use crate::core::{Client, Error, Method, QueryParams, Result};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;

/// Handle for the `amazon` platform. Obtain via [`crate::ScrapeBadger::amazon`].
#[derive(Clone)]
pub struct Amazon {
    client: Client,
}

impl Amazon {
    pub(crate) fn new(client: Client) -> Self {
        Self { client }
    }

    /// Access the underlying transport client.
    pub fn client(&self) -> &Client {
        &self.client
    }

    /// Keyword Suggestions
    ///
    /// Get Amazon search autocomplete suggestions for keyword research.
    /// `GET /v1/amazon/autocomplete`
    pub async fn autocomplete(&self, params: AutocompleteParams) -> Result<AutocompleteResponse> {
        let path = "/v1/amazon/autocomplete".to_string();
        let mut q = QueryParams::new();
        q.opt("query", params.query.as_ref());
        q.opt("domain", params.domain.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Bestsellers
    ///
    /// Top-selling products for a category (browse node).
    /// `GET /v1/amazon/bestsellers`
    pub async fn get_bestsellers(
        &self,
        params: GetBestsellersParams,
    ) -> Result<GetBestsellersResponse> {
        let path = "/v1/amazon/bestsellers".to_string();
        let mut q = QueryParams::new();
        q.opt("domain", params.domain.as_ref());
        q.opt("category", params.category.as_ref());
        q.opt("page", params.page.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// List Categories
    ///
    /// List common Amazon department/category aliases and bestseller nodes.
    /// `GET /v1/amazon/categories`
    pub async fn list_categories(
        &self,
        params: ListCategoriesParams,
    ) -> Result<ListCategoriesResponse> {
        let path = "/v1/amazon/categories".to_string();
        let mut q = QueryParams::new();
        q.opt("domain", params.domain.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Browse Category
    ///
    /// List products within an Amazon browse-node category.
    /// `GET /v1/amazon/category`
    pub async fn browse_category(
        &self,
        params: BrowseCategoryParams,
    ) -> Result<BrowseCategoryResponse> {
        let path = "/v1/amazon/category".to_string();
        let mut q = QueryParams::new();
        q.opt("node", params.node.as_ref());
        q.opt("domain", params.domain.as_ref());
        q.opt("page", params.page.as_ref());
        q.opt("sort_by", params.sort_by.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Today's Deals
    ///
    /// Current Amazon deals (lightning deals, best deals).
    /// `GET /v1/amazon/deals`
    pub async fn get_deals(&self, params: GetDealsParams) -> Result<GetDealsResponse> {
        let path = "/v1/amazon/deals".to_string();
        let mut q = QueryParams::new();
        q.opt("domain", params.domain.as_ref());
        q.opt("category", params.category.as_ref());
        q.opt("page", params.page.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// List Markets
    ///
    /// List all supported Amazon marketplaces.
    /// `GET /v1/amazon/markets`
    pub async fn list_markets(&self, params: ListMarketsParams) -> Result<ListMarketsResponse> {
        let path = "/v1/amazon/markets".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// New Releases
    ///
    /// Newly released products for a category (browse node).
    /// `GET /v1/amazon/new-releases`
    pub async fn get_new_releases(
        &self,
        params: GetNewReleasesParams,
    ) -> Result<GetNewReleasesResponse> {
        let path = "/v1/amazon/new-releases".to_string();
        let mut q = QueryParams::new();
        q.opt("domain", params.domain.as_ref());
        q.opt("category", params.category.as_ref());
        q.opt("page", params.page.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get Product Detail
    ///
    /// Full product detail by ASIN (price, variants, badges, buybox, ranks, ...).
    /// `GET /v1/amazon/products/{asin}`
    pub async fn get_product(
        &self,
        asin: impl AsRef<str>,
        params: GetProductParams,
    ) -> Result<GetProductResponse> {
        let path = format!("/v1/amazon/products/{asin}", asin = asin.as_ref());
        let mut q = QueryParams::new();
        q.opt("domain", params.domain.as_ref());
        q.opt("zip", params.zip.as_ref());
        q.opt("language", params.language.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get Offers
    ///
    /// All third-party offers for an ASIN, including the Buy Box winner.
    /// `GET /v1/amazon/products/{asin}/offers`
    pub async fn get_offers(
        &self,
        asin: impl AsRef<str>,
        params: GetOffersParams,
    ) -> Result<GetOffersResponse> {
        let path = format!("/v1/amazon/products/{asin}/offers", asin = asin.as_ref());
        let mut q = QueryParams::new();
        q.opt("domain", params.domain.as_ref());
        q.opt("zip", params.zip.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get Reviews
    ///
    /// Customer reviews for an ASIN (featured + paginated, with filters).
    /// `GET /v1/amazon/products/{asin}/reviews`
    pub async fn get_reviews(
        &self,
        asin: impl AsRef<str>,
        params: GetReviewsParams,
    ) -> Result<GetReviewsResponse> {
        let path = format!("/v1/amazon/products/{asin}/reviews", asin = asin.as_ref());
        let mut q = QueryParams::new();
        q.opt("domain", params.domain.as_ref());
        q.opt("page", params.page.as_ref());
        q.opt("sort_by", params.sort_by.as_ref());
        q.opt("star", params.star.as_ref());
        q.opt("verified_only", params.verified_only.as_ref());
        q.opt("media_only", params.media_only.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Search Products
    ///
    /// Search the Amazon catalog with filters and sorting.
    /// `GET /v1/amazon/search`
    pub async fn search_products(
        &self,
        params: SearchProductsParams,
    ) -> Result<SearchProductsResponse> {
        let path = "/v1/amazon/search".to_string();
        let mut q = QueryParams::new();
        q.opt("query", params.query.as_ref());
        q.opt("domain", params.domain.as_ref());
        q.opt("page", params.page.as_ref());
        q.opt("sort_by", params.sort_by.as_ref());
        q.opt("category", params.category.as_ref());
        q.opt("min_price", params.min_price.as_ref());
        q.opt("max_price", params.max_price.as_ref());
        q.opt("zip", params.zip.as_ref());
        q.opt("language", params.language.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get Seller
    ///
    /// Seller profile, ratings and feedback summary.
    /// `GET /v1/amazon/sellers/{seller_id}`
    pub async fn get_seller(
        &self,
        seller_id: impl AsRef<str>,
        params: GetSellerParams,
    ) -> Result<GetSellerResponse> {
        let path = format!(
            "/v1/amazon/sellers/{seller_id}",
            seller_id = seller_id.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("domain", params.domain.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Seller Feedback
    ///
    /// Buyer feedback entries for a seller.
    /// `GET /v1/amazon/sellers/{seller_id}/feedback`
    pub async fn get_seller_feedback(
        &self,
        seller_id: impl AsRef<str>,
        params: GetSellerFeedbackParams,
    ) -> Result<GetSellerFeedbackResponse> {
        let path = format!(
            "/v1/amazon/sellers/{seller_id}/feedback",
            seller_id = seller_id.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("domain", params.domain.as_ref());
        q.opt("page", params.page.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Seller Products
    ///
    /// Products listed in a seller's storefront.
    /// `GET /v1/amazon/sellers/{seller_id}/products`
    pub async fn get_seller_products(
        &self,
        seller_id: impl AsRef<str>,
        params: GetSellerProductsParams,
    ) -> Result<GetSellerProductsResponse> {
        let path = format!(
            "/v1/amazon/sellers/{seller_id}/products",
            seller_id = seller_id.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("domain", params.domain.as_ref());
        q.opt("page", params.page.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }
}

// ===== Models =====

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct AmazonPrice {
    /// ISO 4217 currency code.
    pub currency: Option<String>,
    /// Price exactly as displayed on Amazon.
    pub raw: Option<String>,
    /// Currency symbol (e.g. $, £, €).
    pub symbol: Option<String>,
    /// Numeric price value.
    pub value: Option<f64>,
    /// Fields present in the response but not in the spec.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct AutocompleteResponse {
    pub domain: Option<String>,
    pub query: Option<String>,
    pub suggestions: Vec<AutocompleteResponseSuggestionsItem>,
    /// Fields present in the response but not in the spec.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct AutocompleteResponseSuggestionsItem {
    /// Department alias the suggestion is scoped to, if any.
    pub alias: Option<String>,
    /// Suggested search phrase.
    pub value: Option<String>,
    /// Fields present in the response but not in the spec.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct Bestseller {
    pub asin: Option<String>,
    pub image: Option<String>,
    pub link: Option<String>,
    /// Position on the page.
    pub position: Option<i64>,
    pub price: Option<AmazonPrice>,
    /// Best-seller / new-release rank.
    pub rank: Option<i64>,
    pub rating: Option<f64>,
    pub ratings_total: Option<i64>,
    pub title: Option<String>,
    /// Fields present in the response but not in the spec.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct BrowseCategoryResponse {
    pub domain: Option<String>,
    pub node: Option<String>,
    pub pagination: Option<Pagination>,
    pub results: Vec<SearchResult>,
    /// Fields present in the response but not in the spec.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

/// Allowed values for a fixed-value query parameter.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum BrowseCategorySortBy {
    /// `relevance`
    #[serde(rename = "relevance")]
    Relevance,
    /// `price_low_to_high`
    #[serde(rename = "price_low_to_high")]
    PriceLowToHigh,
    /// `price_high_to_low`
    #[serde(rename = "price_high_to_low")]
    PriceHighToLow,
    /// `avg_review`
    #[serde(rename = "avg_review")]
    AvgReview,
    /// `newest`
    #[serde(rename = "newest")]
    Newest,
}

impl std::fmt::Display for BrowseCategorySortBy {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            BrowseCategorySortBy::Relevance => "relevance",
            BrowseCategorySortBy::PriceLowToHigh => "price_low_to_high",
            BrowseCategorySortBy::PriceHighToLow => "price_high_to_low",
            BrowseCategorySortBy::AvgReview => "avg_review",
            BrowseCategorySortBy::Newest => "newest",
        })
    }
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct Deal {
    pub asin: Option<String>,
    pub badge: Option<String>,
    pub deal_price: Option<AmazonPrice>,
    pub deal_type: Option<String>,
    pub discount_percent: Option<i64>,
    pub ends_at: Option<String>,
    pub ends_at_utc: Option<f64>,
    pub image: Option<String>,
    pub is_lightning_deal: Option<bool>,
    pub link: Option<String>,
    pub list_price: Option<AmazonPrice>,
    pub position: Option<i64>,
    pub title: Option<String>,
    /// Fields present in the response but not in the spec.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct GetBestsellersResponse {
    pub category: Option<String>,
    pub domain: Option<String>,
    pub results: Vec<Bestseller>,
    /// Fields present in the response but not in the spec.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct GetDealsResponse {
    pub category: Option<String>,
    pub domain: Option<String>,
    pub results: Vec<Deal>,
    /// Fields present in the response but not in the spec.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct GetNewReleasesResponse {
    pub category: Option<String>,
    pub domain: Option<String>,
    pub results: Vec<Bestseller>,
    /// Fields present in the response but not in the spec.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct GetOffersResponse {
    pub asin: Option<String>,
    pub domain: Option<String>,
    pub offers: Vec<Offer>,
    /// Fields present in the response but not in the spec.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct GetProductResponse {
    pub domain: Option<String>,
    pub product: Option<Product>,
    /// Fields present in the response but not in the spec.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct GetReviewsResponse {
    pub asin: Option<String>,
    pub domain: Option<String>,
    pub pagination: Option<Pagination>,
    /// Overall average product rating.
    pub rating: Option<f64>,
    pub rating_breakdown: Option<GetReviewsResponseRatingBreakdown>,
    /// Total number of ratings for the product.
    pub ratings_total: Option<i64>,
    pub reviews: Vec<Review>,
    /// Fields present in the response but not in the spec.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct GetReviewsResponseRatingBreakdown {
    pub five_star: Option<i64>,
    pub four_star: Option<i64>,
    pub one_star: Option<i64>,
    pub three_star: Option<i64>,
    pub two_star: Option<i64>,
    /// Fields present in the response but not in the spec.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

/// Allowed values for a fixed-value query parameter.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum GetReviewsSortBy {
    /// `helpful`
    #[serde(rename = "helpful")]
    Helpful,
    /// `recent`
    #[serde(rename = "recent")]
    Recent,
}

impl std::fmt::Display for GetReviewsSortBy {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            GetReviewsSortBy::Helpful => "helpful",
            GetReviewsSortBy::Recent => "recent",
        })
    }
}

/// Allowed values for a fixed-value query parameter.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum GetReviewsStar {
    /// `one_star`
    #[serde(rename = "one_star")]
    OneStar,
    /// `two_star`
    #[serde(rename = "two_star")]
    TwoStar,
    /// `three_star`
    #[serde(rename = "three_star")]
    ThreeStar,
    /// `four_star`
    #[serde(rename = "four_star")]
    FourStar,
    /// `five_star`
    #[serde(rename = "five_star")]
    FiveStar,
    /// `positive`
    #[serde(rename = "positive")]
    Positive,
    /// `critical`
    #[serde(rename = "critical")]
    Critical,
}

impl std::fmt::Display for GetReviewsStar {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            GetReviewsStar::OneStar => "one_star",
            GetReviewsStar::TwoStar => "two_star",
            GetReviewsStar::ThreeStar => "three_star",
            GetReviewsStar::FourStar => "four_star",
            GetReviewsStar::FiveStar => "five_star",
            GetReviewsStar::Positive => "positive",
            GetReviewsStar::Critical => "critical",
        })
    }
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct GetSellerFeedbackResponse {
    pub domain: Option<String>,
    pub feedback: Vec<GetSellerFeedbackResponseFeedbackItem>,
    pub pagination: Option<Pagination>,
    pub seller_id: Option<String>,
    /// Fields present in the response but not in the spec.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct GetSellerFeedbackResponseFeedbackItem {
    /// Feedback comment text.
    pub body: Option<String>,
    /// ISO 8601 timestamp of the feedback.
    pub date_at: Option<String>,
    /// Raw date string as shown on Amazon.
    pub date_raw: Option<String>,
    /// Buyer display name, if shown.
    pub rater: Option<String>,
    /// Star rating left by the buyer (1-5).
    pub rating: Option<i64>,
    /// Fields present in the response but not in the spec.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct GetSellerProductsResponse {
    pub domain: Option<String>,
    pub pagination: Option<Pagination>,
    pub results: Vec<SearchResult>,
    pub seller_id: Option<String>,
    /// Fields present in the response but not in the spec.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct GetSellerResponse {
    pub domain: Option<String>,
    pub seller: Option<Seller>,
    /// Fields present in the response but not in the spec.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct ListCategoriesResponse {
    pub categories: Vec<ListCategoriesResponseCategoriesItem>,
    pub domain: Option<String>,
    /// Fields present in the response but not in the spec.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct ListCategoriesResponseCategoriesItem {
    /// Category alias usable in the search category parameter (the i= value).
    pub alias: Option<String>,
    /// Browse-node slug usable with bestsellers / new-releases.
    pub bestsellers_node: Option<String>,
    /// Human-readable department name.
    pub name: Option<String>,
    /// Fields present in the response but not in the spec.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct ListMarketsResponse {
    pub markets: Vec<ListMarketsResponseMarketsItem>,
    /// Fields present in the response but not in the spec.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct ListMarketsResponseMarketsItem {
    /// Market code (e.g. US, UK, DE).
    pub code: Option<String>,
    /// ISO country code used for proxy geo-targeting.
    pub country_code: Option<String>,
    /// ISO 4217 currency code.
    pub currency: Option<String>,
    /// Amazon domain TLD for this market (e.g. com, co.uk).
    pub domain: Option<String>,
    /// Default locale for this market.
    pub language: Option<String>,
    /// Marketplace country name.
    pub name: Option<String>,
    /// Fields present in the response but not in the spec.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct Offer {
    /// Whether this offer currently wins the Buy Box.
    pub buybox_winner: Option<bool>,
    /// is_new, title, comments.
    pub condition: HashMap<String, Value>,
    /// is_free, fulfilled_by_amazon, date, price.
    pub delivery: HashMap<String, Value>,
    pub is_prime: Option<bool>,
    pub maximum_order_quantity: Option<i64>,
    pub minimum_order_quantity: Option<i64>,
    pub position: Option<i64>,
    pub price: Option<AmazonPrice>,
    /// Seller summary: name, id, link, rating, ratings_total, ratings_percentage_positive.
    pub seller: HashMap<String, Value>,
    /// Fields present in the response but not in the spec.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct Pagination {
    /// Current page number.
    pub current_page: Option<i64>,
    /// Total number of pages available.
    pub total_pages: Option<i64>,
    /// Total number of results across all pages.
    pub total_results: Option<i64>,
    /// Fields present in the response but not in the spec.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct Product {
    pub also_bought: Vec<String>,
    pub answered_questions: Option<i64>,
    pub asin: Option<String>,
    pub attributes: HashMap<String, Value>,
    pub availability: Option<String>,
    /// amazons_choice, amazons_choice_keyword, best_seller, prime, climate_pledge_friendly.
    pub badges: HashMap<String, Value>,
    /// Best-seller ranks with rank, category, link.
    pub bestsellers_rank: Vec<HashMap<String, Value>>,
    pub bought_past_month: Option<String>,
    pub brand: Option<String>,
    /// Buy Box winner: seller_name, seller_id, price, fulfillment.
    pub buybox: HashMap<String, Value>,
    /// Breadcrumb categories.
    pub categories: Vec<HashMap<String, Value>>,
    pub country_of_origin: Option<String>,
    pub coupon: Option<HashMap<String, Value>>,
    pub deal: Option<HashMap<String, Value>>,
    pub delivery: Option<HashMap<String, Value>>,
    pub description: Option<String>,
    pub dimensions: Option<String>,
    pub discount_percent: Option<i64>,
    pub feature_bullets: Vec<String>,
    pub first_available: Option<String>,
    pub frequently_bought_together: Vec<String>,
    pub fulfilled_by: Option<String>,
    pub has_aplus_content: Option<bool>,
    pub images: Vec<String>,
    pub images_count: Option<i64>,
    pub in_stock: Option<bool>,
    pub is_amazon_seller: Option<bool>,
    pub link: Option<String>,
    pub list_price: Option<AmazonPrice>,
    pub main_image: Option<String>,
    pub manufacturer: Option<String>,
    pub model_number: Option<String>,
    pub parent_asin: Option<String>,
    pub price: Option<AmazonPrice>,
    pub rating: Option<f64>,
    /// Percentage of ratings per star bucket (five_star ... one_star).
    pub rating_breakdown: HashMap<String, Value>,
    pub ratings_total: Option<i64>,
    pub savings_amount: Option<AmazonPrice>,
    pub scraped_at: Option<String>,
    pub scraped_utc: Option<f64>,
    pub ships_from: Option<String>,
    pub sold_by: Option<String>,
    pub specifications: HashMap<String, Value>,
    pub title: Option<String>,
    pub top_reviews: Vec<Review>,
    pub variant_asins: Vec<String>,
    /// Variation children with asin, attributes, price, is_current.
    pub variants: Vec<HashMap<String, Value>>,
    pub videos: Vec<String>,
    pub videos_count: Option<i64>,
    pub weight: Option<String>,
    /// Fields present in the response but not in the spec.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct Review {
    pub body: Option<String>,
    pub date_at: Option<String>,
    pub date_raw: Option<String>,
    pub date_utc: Option<f64>,
    pub helpful_votes: Option<i64>,
    pub id: Option<String>,
    pub images: Vec<String>,
    pub is_global_review: Option<bool>,
    /// Reviewer profile: name, link, id, image.
    pub profile: HashMap<String, Value>,
    /// Star rating left by the reviewer (1-5).
    pub rating: Option<i64>,
    pub review_country: Option<String>,
    pub title: Option<String>,
    pub variant: Option<String>,
    pub verified_purchase: Option<bool>,
    pub vine_program: Option<bool>,
    /// Fields present in the response but not in the spec.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct SearchProductsResponse {
    /// Marketplace domain that was searched.
    pub domain: Option<String>,
    pub pagination: Option<Pagination>,
    /// The search query that was executed.
    pub query: Option<String>,
    pub results: Vec<SearchResult>,
    /// Fields present in the response but not in the spec.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

/// Allowed values for a fixed-value query parameter.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum SearchProductsSortBy {
    /// `relevance`
    #[serde(rename = "relevance")]
    Relevance,
    /// `price_low_to_high`
    #[serde(rename = "price_low_to_high")]
    PriceLowToHigh,
    /// `price_high_to_low`
    #[serde(rename = "price_high_to_low")]
    PriceHighToLow,
    /// `avg_review`
    #[serde(rename = "avg_review")]
    AvgReview,
    /// `newest`
    #[serde(rename = "newest")]
    Newest,
}

impl std::fmt::Display for SearchProductsSortBy {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            SearchProductsSortBy::Relevance => "relevance",
            SearchProductsSortBy::PriceLowToHigh => "price_low_to_high",
            SearchProductsSortBy::PriceHighToLow => "price_high_to_low",
            SearchProductsSortBy::AvgReview => "avg_review",
            SearchProductsSortBy::Newest => "newest",
        })
    }
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct SearchResult {
    /// Amazon Standard Identification Number.
    pub asin: Option<String>,
    /// Availability/stock message.
    pub availability: Option<String>,
    /// Purchase-volume hint (e.g. "5K+ bought in past month").
    pub bought_past_month: Option<String>,
    /// Coupon text, if any.
    pub coupon: Option<String>,
    /// Primary product image URL.
    pub image: Option<String>,
    /// Whether the item has the Amazon's Choice badge.
    pub is_amazons_choice: Option<bool>,
    /// Whether the item has the Best Seller badge.
    pub is_best_seller: Option<bool>,
    /// Whether the item is Prime-eligible.
    pub is_prime: Option<bool>,
    /// Whether the result is a sponsored placement.
    pub is_sponsored: Option<bool>,
    /// Full URL to the product page.
    pub link: Option<String>,
    pub list_price: Option<AmazonPrice>,
    /// Position of the result on the page (1-based).
    pub position: Option<i64>,
    pub price: Option<AmazonPrice>,
    /// Average star rating (0-5).
    pub rating: Option<f64>,
    /// Total number of ratings.
    pub ratings_total: Option<i64>,
    /// Product title.
    pub title: Option<String>,
    /// Unit price string (e.g. "$0.50 / count").
    pub unit_price: Option<String>,
    /// Fields present in the response but not in the spec.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct Seller {
    pub business_address: Option<String>,
    pub business_name: Option<String>,
    /// Feedback windows (lifetime, 12mo, 90d, 30d) each with positive, neutral, negative, count.
    pub feedback: HashMap<String, Value>,
    pub link: Option<String>,
    pub member_since: Option<String>,
    pub name: Option<String>,
    pub rating: Option<f64>,
    pub ratings_percentage_positive: Option<i64>,
    pub ratings_total: Option<i64>,
    pub seller_id: Option<String>,
    /// Fields present in the response but not in the spec.
    #[serde(flatten)]
    pub extra: HashMap<String, Value>,
}

/// Parameters for [`AutocompleteParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct AutocompleteParams {
    /// Partial search term to expand into suggestions.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    /// Amazon marketplace TLD or code (com, co.uk, de, ...).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
}

/// Parameters for [`GetBestsellersParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetBestsellersParams {
    /// Amazon marketplace TLD or code (com, co.uk, de, ...).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    /// Bestsellers node id or category slug (e.g. electronics).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    /// Page number (each page covers 50 ranks; max 2).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
}

/// Parameters for [`ListCategoriesParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ListCategoriesParams {
    /// Amazon marketplace TLD or code. Category aliases are scoped per marketplace.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
}

/// Parameters for [`BrowseCategoryParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct BrowseCategoryParams {
    /// Amazon browse-node id to list products from.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub node: Option<String>,
    /// Amazon marketplace TLD or code (com, co.uk, de, ...).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    /// Page number for paginated results.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
    /// Sort order for results.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sort_by: Option<BrowseCategorySortBy>,
}

/// Parameters for [`GetDealsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetDealsParams {
    /// Amazon marketplace TLD or code (com, co.uk, de, ...).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    /// Category alias to scope the deals feed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    /// Page number for paginated deals.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
}

/// Parameters for [`ListMarketsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ListMarketsParams {}

/// Parameters for [`GetNewReleasesParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetNewReleasesParams {
    /// Amazon marketplace TLD or code (com, co.uk, de, ...).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    /// New-releases node id or category slug.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    /// Page number (each page covers 50 ranks; max 2).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
}

/// Parameters for [`GetProductParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetProductParams {
    /// Amazon marketplace TLD or code (com, co.uk, de, ...).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    /// Delivery postal/zip code for a localized buybox.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub zip: Option<String>,
    /// Locale for the product page, e.g. en_US, de_DE.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
}

/// Parameters for [`GetOffersParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetOffersParams {
    /// Amazon marketplace TLD or code (com, co.uk, de, ...).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    /// Delivery postal/zip code for localized offers and delivery estimates.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub zip: Option<String>,
}

/// Parameters for [`GetReviewsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetReviewsParams {
    /// Amazon marketplace TLD or code (com, co.uk, de, ...).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    /// Page number for paginated reviews.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
    /// Sort order for reviews.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sort_by: Option<GetReviewsSortBy>,
    /// Filter reviews by star rating or sentiment.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub star: Option<GetReviewsStar>,
    /// Only return reviews from verified purchases.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub verified_only: Option<bool>,
    /// Only return reviews that include images or video.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub media_only: Option<bool>,
}

/// Parameters for [`SearchProductsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct SearchProductsParams {
    /// Search keywords.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    /// Amazon marketplace TLD or code (com, co.uk, de, fr, ...).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    /// Page number for paginated results.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
    /// Sort order for results.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sort_by: Option<SearchProductsSortBy>,
    /// Department/category alias to scope the search (the i= parameter).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    /// Minimum price filter in the marketplace's local currency.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_price: Option<f64>,
    /// Maximum price filter in the marketplace's local currency.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_price: Option<f64>,
    /// Delivery postal/zip code for localized pricing.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub zip: Option<String>,
    /// Locale for results, e.g. en_US, fr_FR.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
}

/// Parameters for [`GetSellerParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetSellerParams {
    /// Amazon marketplace TLD or code (com, co.uk, de, ...).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
}

/// Parameters for [`GetSellerFeedbackParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetSellerFeedbackParams {
    /// Amazon marketplace TLD or code (com, co.uk, de, ...).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    /// Page number for paginated feedback entries.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
}

/// Parameters for [`GetSellerProductsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetSellerProductsParams {
    /// Amazon marketplace TLD or code (com, co.uk, de, ...).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    /// Page number for paginated storefront results.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
}
