// @generated by `cargo run -p xtask -- gen` from specs/loopnet.json — do not edit by hand.
#![allow(clippy::all)]
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    non_snake_case,
    rustdoc::all
)]

use crate::core::{Client, Error, Method, QueryParams, Result};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;

/// Handle for the `loopnet` platform. Obtain via [`crate::ScrapeBadger::loopnet`].
#[derive(Clone)]
pub struct Loopnet {
    client: Client,
}

impl Loopnet {
    pub(crate) fn new(client: Client) -> Self {
        Self { client }
    }

    /// Access the underlying transport client.
    pub fn client(&self) -> &Client {
        &self.client
    }

    /// Get broker profile
    ///
    /// Get a LoopNet broker profile + their listings by slug + id.
    /// `GET /v1/loopnet/brokers/{slug}/{broker_id}`
    pub async fn get_broker(
        &self,
        slug: impl AsRef<str>,
        broker_id: impl AsRef<str>,
        params: GetBrokerParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/loopnet/brokers/{slug}/{broker_id}",
            slug = slug.as_ref(),
            broker_id = broker_id.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("market", params.market.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get listing detail
    ///
    /// Get a single LoopNet listing's full detail by its numeric id.
    /// `GET /v1/loopnet/listings/{listing_id}`
    pub async fn get_listing(
        &self,
        listing_id: impl AsRef<str>,
        params: GetListingParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/loopnet/listings/{listing_id}",
            listing_id = listing_id.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("market", params.market.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// List coverage markets
    ///
    /// List LoopNet coverage markets (US, CA, UK, FR, ES).
    /// `GET /v1/loopnet/markets`
    pub async fn list_markets(&self, params: ListMarketsParams) -> Result<Value> {
        let path = "/v1/loopnet/markets".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// List property types
    ///
    /// List LoopNet property-type facets accepted by /search.
    /// `GET /v1/loopnet/property-types`
    pub async fn list_property_types(&self, params: ListPropertyTypesParams) -> Result<Value> {
        let path = "/v1/loopnet/property-types".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Search commercial real estate
    ///
    /// Search LoopNet for-lease / for-sale / auction listings across all markets.
    /// `GET /v1/loopnet/search`
    pub async fn search(&self, params: SearchParams) -> Result<Value> {
        let path = "/v1/loopnet/search".to_string();
        let mut q = QueryParams::new();
        q.opt("location", params.location.as_ref());
        q.opt("market", params.market.as_ref());
        q.opt("listing_type", params.listing_type.as_ref());
        q.opt("property_type", params.property_type.as_ref());
        q.opt("page", params.page.as_ref());
        q.opt("min_price", params.min_price.as_ref());
        q.opt("max_price", params.max_price.as_ref());
        q.opt("price_type", params.price_type.as_ref());
        q.opt("min_size", params.min_size.as_ref());
        q.opt("max_size", params.max_size.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }
}

// ===== Models =====

/// Parameters for [`GetBrokerParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetBrokerParams {
    /// us|ca|uk|fr|es
    #[serde(skip_serializing_if = "Option::is_none")]
    pub market: Option<String>,
}

/// Parameters for [`GetListingParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetListingParams {
    /// us|ca|uk|fr|es
    #[serde(skip_serializing_if = "Option::is_none")]
    pub market: Option<String>,
}

/// Parameters for [`ListMarketsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ListMarketsParams {}

/// Parameters for [`ListPropertyTypesParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ListPropertyTypesParams {}

/// Parameters for [`SearchParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct SearchParams {
    /// City/state, ZIP, state code, or 'usa'
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    /// us|ca|uk|fr|es
    #[serde(skip_serializing_if = "Option::is_none")]
    pub market: Option<String>,
    /// for-lease|for-sale|auctions
    #[serde(skip_serializing_if = "Option::is_none")]
    pub listing_type: Option<String>,
    /// Slug from /property-types
    #[serde(skip_serializing_if = "Option::is_none")]
    pub property_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_price: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_price: Option<i64>,
    /// unit | sf | acre
    #[serde(skip_serializing_if = "Option::is_none")]
    pub price_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_size: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_size: Option<i64>,
}
