//! ScrapeBadger Rust SDK code generator.
//!
//! Reads the vendored OpenAPI specs in `specs/*.json` and emits one
//! `crates/scrapebadger/src/<platform>/generated.rs` per platform containing:
//!   * response + request-parameter models (serde structs / type aliases),
//!   * a platform handle struct with one async method per endpoint.
//!
//! Run with: `cargo run -p xtask -- gen`
//!
//! The specs are inconsistent (generated by different backends), so the
//! generator is deliberately defensive — see `docs`/ARCHITECTURE for the
//! catalogue of quirks it normalizes (4 nullable encodings, untyped Reddit
//! responses, anonymous inline objects, FastAPI operationIds, etc.).

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

use serde_json::{Map, Value};

mod cli_gen;
mod naming;
mod schema;

use naming::{method_name, sanitize_field, sanitize_type};
use schema::SchemaCtx;

/// (spec file stem, platform module name, platform handle struct name).
const PLATFORMS: &[(&str, &str, &str)] = &[
    ("account", "account", "Account"),
    ("amazon", "amazon", "Amazon"),
    ("google", "google", "Google"),
    ("reddit", "reddit", "Reddit"),
    ("twitter", "twitter", "Twitter"),
    ("vinted", "vinted", "Vinted"),
    ("web-scraping", "web", "Web"),
];

fn main() {
    let cmd = std::env::args().nth(1).unwrap_or_default();
    if cmd != "gen" {
        eprintln!("usage: cargo run -p xtask -- gen");
        std::process::exit(2);
    }

    let root = workspace_root();
    let specs_dir = root.join("specs");
    let out_dir = root.join("crates/scrapebadger/src");

    let mut total_ops = 0usize;
    let mut written: Vec<PathBuf> = Vec::new();
    for (stem, module, handle) in PLATFORMS {
        let spec_path = specs_dir.join(format!("{stem}.json"));
        let spec: Value = serde_json::from_slice(
            &std::fs::read(&spec_path).unwrap_or_else(|e| panic!("read {spec_path:?}: {e}")),
        )
        .unwrap_or_else(|e| panic!("parse {spec_path:?}: {e}"));

        let (code, ops) = generate_platform(module, handle, &spec);
        total_ops += ops;

        let dir = out_dir.join(module);
        std::fs::create_dir_all(&dir).unwrap();
        let dest = dir.join("generated.rs");
        std::fs::write(&dest, code).unwrap();
        println!("{module:>8}: {ops:>3} endpoints -> {}", rel(&dest, &root));
        written.push(dest);
    }
    println!("\ntotal endpoints generated: {total_ops}");

    // CLI descriptor table + docs reference (same source of truth).
    cli_gen::generate(&root);
    written.push(out_dir.join("cli/generated.rs"));

    // Format the emitted Rust so committed output is rustfmt-clean (keeps the
    // `cargo fmt --check` CI gate green; markdown docs are left untouched).
    rustfmt(&written);
}

/// Run `rustfmt` over the generated `.rs` files. A missing `rustfmt` is a hard
/// error: unformatted output would fail CI, so the generator must not emit it.
fn rustfmt(files: &[PathBuf]) {
    use std::process::Command;
    let status = Command::new("rustfmt")
        .arg("--edition")
        .arg("2021")
        .args(files)
        .status()
        .expect("run rustfmt (is the `rustfmt` component installed?)");
    assert!(status.success(), "rustfmt failed on generated output");
    println!("rustfmt: formatted {} generated file(s)", files.len());
}

/// Generate the full `generated.rs` source for one platform.
fn generate_platform(module: &str, handle: &str, spec: &Value) -> (String, usize) {
    let mut ctx = SchemaCtx::new(spec);

    // 1. Pre-register every named component schema so $ref resolution is stable.
    if let Some(schemas) = spec
        .pointer("/components/schemas")
        .and_then(Value::as_object)
    {
        for name in schemas.keys() {
            ctx.register_named(name);
        }
    }

    // 2. Emit each named component schema.
    if let Some(schemas) = spec
        .pointer("/components/schemas")
        .and_then(Value::as_object)
    {
        for (name, sch) in schemas {
            ctx.emit_named(&sanitize_type(name), sch);
        }
    }

    // 3. Walk operations -> param structs + methods.
    let mut methods: Vec<String> = Vec::new();
    let mut used_method_names: BTreeSet<String> = BTreeSet::new();
    let mut ops = 0usize;

    let mut paths: Vec<(&String, &Value)> = spec
        .get("paths")
        .and_then(Value::as_object)
        .map(|m| m.iter().collect())
        .unwrap_or_default();
    paths.sort_by(|a, b| a.0.cmp(b.0));

    for (path, item) in paths {
        let item = match item.as_object() {
            Some(o) => o,
            None => continue,
        };
        for verb in ["get", "post", "put", "patch", "delete"] {
            let op = match item.get(verb).and_then(Value::as_object) {
                Some(o) => o,
                None => continue,
            };
            // Skip health/ping endpoints — not part of the data surface.
            if path.contains("/health") {
                continue;
            }
            if let Some(m) =
                generate_operation(module, path, verb, op, &mut ctx, &mut used_method_names)
            {
                methods.push(m);
                ops += 1;
            }
        }
    }

    // 4. Assemble the file.
    let mut out = String::new();
    out.push_str(&format!(
        "// @generated by `cargo run -p xtask -- gen` from specs/{}.json — do not edit by hand.\n",
        spec_stem_for(module)
    ));
    out.push_str("#![allow(clippy::all)]\n");
    out.push_str(
        "#![allow(dead_code, unused_imports, unused_variables, non_snake_case, rustdoc::all)]\n\n",
    );
    out.push_str("use serde::{Deserialize, Serialize};\n");
    out.push_str("use std::collections::HashMap;\n");
    out.push_str("use serde_json::Value;\n");
    out.push_str("use crate::core::{Client, Error, Method, QueryParams, Result};\n\n");

    out.push_str(&format!(
        "/// Handle for the `{module}` platform. Obtain via [`crate::ScrapeBadger::{module}`].\n"
    ));
    out.push_str("#[derive(Clone)]\n");
    out.push_str(&format!(
        "pub struct {handle} {{\n    client: Client,\n}}\n\n"
    ));
    out.push_str(&format!("impl {handle} {{\n"));
    out.push_str(
        "    pub(crate) fn new(client: Client) -> Self {\n        Self { client }\n    }\n\n",
    );
    out.push_str("    /// Access the underlying transport client.\n");
    out.push_str("    pub fn client(&self) -> &Client {\n        &self.client\n    }\n\n");
    for m in &methods {
        out.push_str(m);
        out.push('\n');
    }
    out.push_str("}\n\n");

    // Models (sorted, deduped).
    out.push_str("// ===== Models =====\n\n");
    for def in ctx.take_defs() {
        out.push_str(&def);
        out.push_str("\n\n");
    }

    (out, ops)
}

/// Emit one async method (+ its `Params` struct) for a single operation.
fn generate_operation(
    module: &str,
    path: &str,
    verb: &str,
    op: &Map<String, Value>,
    ctx: &mut SchemaCtx,
    used: &mut BTreeSet<String>,
) -> Option<String> {
    let op_id = op.get("operationId").and_then(Value::as_str).unwrap_or("");
    let mut name = method_name(op_id, path, module);
    // Deduplicate within the platform.
    if used.contains(&name) {
        let mut i = 2;
        while used.contains(&format!("{name}_{i}")) {
            i += 1;
        }
        name = format!("{name}_{i}");
    }
    used.insert(name.clone());

    let pascal = naming::to_pascal(&name);
    let params_struct = format!("{pascal}Params");

    // Collect parameters.
    let mut path_params: Vec<String> = Vec::new();
    let mut query_fields: Vec<ParamField> = Vec::new();

    if let Some(params) = op.get("parameters").and_then(Value::as_array) {
        for p in params {
            let p = match p.as_object() {
                Some(o) => o,
                None => continue,
            };
            let pname = p.get("name").and_then(Value::as_str).unwrap_or("");
            let loc = p.get("in").and_then(Value::as_str).unwrap_or("");
            let schema = p.get("schema").cloned().unwrap_or(Value::Null);
            let desc = p
                .get("description")
                .and_then(Value::as_str)
                .map(str::to_string);
            match loc {
                "path" => path_params.push(naming::sanitize_ident(pname)),
                "query" => {
                    let enum_hint = format!("{pascal}{}", naming::to_pascal(pname));
                    let (ty, is_array) = ctx.query_param_type(&schema, &enum_hint);
                    let (ident, rename) = sanitize_field(pname);
                    query_fields.push(ParamField {
                        orig: pname.to_string(),
                        ident,
                        rename,
                        ty,
                        is_array,
                        desc,
                    });
                }
                _ => {}
            }
        }
    }

    // Request body (Twitter stream, web scraping) -> body fields.
    let mut body_fields: Vec<ParamField> = Vec::new();
    if let Some(schema) = op
        .get("requestBody")
        .and_then(|v| v.pointer("/content/application~1json/schema"))
        .cloned()
    {
        let resolved = ctx.resolve(&schema);
        if let Some(props) = resolved.get("properties").and_then(Value::as_object) {
            for (pname, psch) in props {
                let ty = ctx.rust_type(psch, &format!("{pascal}{}", naming::to_pascal(pname)));
                let (ident, rename) = sanitize_field(pname);
                let desc = psch
                    .get("description")
                    .and_then(Value::as_str)
                    .map(str::to_string);
                body_fields.push(ParamField {
                    orig: pname.to_string(),
                    ident,
                    rename,
                    ty,
                    is_array: false,
                    desc,
                });
            }
        }
    }

    // Resolve the success response type.
    let resp_ty = ctx.response_type(op, &format!("{pascal}Response"));

    // Build the Params struct.
    let mut all_fields = query_fields.clone();
    all_fields.extend(body_fields.clone());
    ctx.push_def(render_params_struct(&params_struct, &all_fields));

    // Build the method.
    let mut m = String::new();
    if let Some(summary) = op.get("summary").and_then(Value::as_str) {
        for line in summary.lines() {
            m.push_str(&format!("    /// {}\n", line.trim()));
        }
    }
    if let Some(desc) = op.get("description").and_then(Value::as_str) {
        m.push_str("    ///\n");
        for line in desc.lines().take(8) {
            m.push_str(&format!("    /// {}\n", line.trim()));
        }
    }
    m.push_str(&format!("    /// `{} {}`\n", verb.to_uppercase(), path));

    // Signature.
    let mut args = String::from("&self");
    for pp in &path_params {
        args.push_str(&format!(", {pp}: impl AsRef<str>"));
    }
    args.push_str(&format!(", params: {params_struct}"));
    m.push_str(&format!(
        "    pub async fn {name}({args}) -> Result<{resp_ty}> {{\n"
    ));

    // Path with substitution.
    let path_expr = build_path_expr(path, &path_params);
    m.push_str(&format!("        let path = {path_expr};\n"));

    // Query.
    if query_fields.is_empty() {
        m.push_str("        let query: Vec<(String, String)> = Vec::new();\n");
    } else {
        m.push_str("        let mut q = QueryParams::new();\n");
        for f in &query_fields {
            if f.is_array {
                m.push_str(&format!(
                    "        q.list(\"{}\", params.{}.as_ref());\n",
                    f.orig, f.ident
                ));
            } else {
                m.push_str(&format!(
                    "        q.opt(\"{}\", params.{}.as_ref());\n",
                    f.orig, f.ident
                ));
            }
        }
        m.push_str("        let query = q.into_pairs();\n");
    }

    // Body.
    if body_fields.is_empty() {
        m.push_str("        let body = None;\n");
    } else {
        m.push_str("        let mut body = serde_json::Map::new();\n");
        for f in &body_fields {
            m.push_str(&format!(
                "        if let Some(v) = &params.{} {{ body.insert(\"{}\".to_string(), serde_json::json!(v)); }}\n",
                f.ident, f.orig
            ));
        }
        m.push_str(
            "        let body = if body.is_empty() { None } else { Some(Value::Object(body)) };\n",
        );
    }

    let method_const = match verb {
        "get" => "Method::GET",
        "post" => "Method::POST",
        "put" => "Method::PUT",
        "patch" => "Method::PATCH",
        "delete" => "Method::DELETE",
        _ => "Method::GET",
    };
    m.push_str(&format!(
        "        self.client.send({method_const}, &path, &query, body).await\n"
    ));
    m.push_str("    }\n");

    Some(m)
}

#[derive(Clone)]
struct ParamField {
    orig: String,
    ident: String,
    rename: bool,
    ty: String,
    is_array: bool,
    desc: Option<String>,
}

/// Render a `#[derive(Default)]` params struct; every field is optional and
/// skipped when `None` so the server's documented defaults apply.
fn render_params_struct(name: &str, fields: &[ParamField]) -> String {
    let mut s = String::new();
    s.push_str(&format!(
        "/// Parameters for [`{}`]. All fields optional; required ones are noted per method.\n",
        name
    ));
    s.push_str("#[derive(Debug, Clone, Default, Serialize)]\n");
    s.push_str(&format!("pub struct {name} {{\n"));
    for f in fields {
        if let Some(d) = &f.desc {
            for line in d.lines().take(2) {
                s.push_str(&format!("    /// {}\n", line.trim()));
            }
        }
        let ty = if f.is_array {
            format!("Option<Vec<{}>>", strip_option(&f.ty))
        } else {
            ensure_option(&f.ty)
        };
        s.push_str("    #[serde(skip_serializing_if = \"Option::is_none\")]\n");
        if f.rename {
            s.push_str(&format!("    #[serde(rename = \"{}\")]\n", f.orig));
        }
        s.push_str(&format!("    pub {}: {},\n", f.ident, ty));
    }
    s.push_str("}\n");
    s
}

fn ensure_option(ty: &str) -> String {
    if ty.starts_with("Option<") {
        ty.to_string()
    } else {
        format!("Option<{ty}>")
    }
}

fn strip_option(ty: &str) -> String {
    ty.strip_prefix("Option<")
        .and_then(|s| s.strip_suffix('>'))
        .unwrap_or(ty)
        .to_string()
}

/// Build a `format!`/`String` expression for the request path, substituting
/// path parameters by name (Rust 2021 inline format captures).
fn build_path_expr(path: &str, path_params: &[String]) -> String {
    if path_params.is_empty() {
        return format!("\"{path}\".to_string()");
    }
    // Re-emit the path literal with `{name}` placeholders preserved, binding
    // each param via `as_ref()` so `impl AsRef<str>` args work in format!.
    let mut binds = String::new();
    for p in path_params {
        binds.push_str(&format!(", {p} = {p}.as_ref()"));
    }
    format!("format!(\"{path}\"{binds})")
}

fn spec_stem_for(module: &str) -> &str {
    PLATFORMS
        .iter()
        .find(|(_, m, _)| *m == module)
        .map(|(s, _, _)| *s)
        .unwrap_or(module)
}

fn workspace_root() -> PathBuf {
    // xtask runs from the workspace root under `cargo run`; fall back to CARGO_MANIFEST_DIR/..
    if let Ok(dir) = std::env::var("CARGO_MANIFEST_DIR") {
        let p = PathBuf::from(dir);
        if let Some(parent) = p.parent() {
            if parent.join("specs").is_dir() {
                return parent.to_path_buf();
            }
        }
    }
    std::env::current_dir().unwrap()
}

fn rel(p: &Path, root: &Path) -> String {
    p.strip_prefix(root)
        .unwrap_or(p)
        .to_string_lossy()
        .to_string()
}
