// @generated by `cargo run -p xtask -- gen` from specs/tiktok.json — do not edit by hand.
#![allow(clippy::all)]
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    non_snake_case,
    rustdoc::all
)]

use crate::core::{Client, Error, Method, QueryParams, Result};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;

/// Handle for the `tiktok` platform. Obtain via [`crate::ScrapeBadger::tiktok`].
#[derive(Clone)]
pub struct Tiktok {
    client: Client,
}

impl Tiktok {
    pub(crate) fn new(client: Client) -> Self {
        Self { client }
    }

    /// Access the underlying transport client.
    pub fn client(&self) -> &Client {
        &self.client
    }

    /// Search the TikTok Ad Library
    ///
    /// Search TikTok's Commercial Content Library (ad transparency) by keyword or advertiser.
    /// `GET /v1/tiktok/ads/search`
    pub async fn search_ads(&self, params: SearchAdsParams) -> Result<Value> {
        let path = "/v1/tiktok/ads/search".to_string();
        let mut q = QueryParams::new();
        q.opt("query", params.query.as_ref());
        q.opt("advertiser_id", params.advertiser_id.as_ref());
        q.opt("region", params.region.as_ref());
        q.opt("days", params.days.as_ref());
        q.opt("sort", params.sort.as_ref());
        q.opt("offset", params.offset.as_ref());
        q.opt("search_id", params.search_id.as_ref());
        q.opt("count", params.count.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get comment replies
    ///
    /// Get replies to a TikTok comment (best-effort).
    /// `GET /v1/tiktok/comments/{comment_id}/replies`
    pub async fn get_comment_replies(
        &self,
        comment_id: impl AsRef<str>,
        params: GetCommentRepliesParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/tiktok/comments/{comment_id}/replies",
            comment_id = comment_id.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("video_id", params.video_id.as_ref());
        q.opt("region", params.region.as_ref());
        q.opt("count", params.count.as_ref());
        q.opt("cursor", params.cursor.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get hashtag detail
    ///
    /// Get TikTok hashtag/challenge detail.
    /// `GET /v1/tiktok/hashtags/{name}`
    pub async fn get_hashtag(
        &self,
        name: impl AsRef<str>,
        params: GetHashtagParams,
    ) -> Result<Value> {
        let path = format!("/v1/tiktok/hashtags/{name}", name = name.as_ref());
        let mut q = QueryParams::new();
        q.opt("region", params.region.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get hashtag videos
    ///
    /// Get videos tagged with a TikTok hashtag.
    /// `GET /v1/tiktok/hashtags/{name}/videos`
    pub async fn get_hashtag_videos(
        &self,
        name: impl AsRef<str>,
        params: GetHashtagVideosParams,
    ) -> Result<Value> {
        let path = format!("/v1/tiktok/hashtags/{name}/videos", name = name.as_ref());
        let mut q = QueryParams::new();
        q.opt("region", params.region.as_ref());
        q.opt("count", params.count.as_ref());
        q.opt("cursor", params.cursor.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get music/sound detail
    ///
    /// Get TikTok sound/music detail.
    /// `GET /v1/tiktok/music/{music_id}`
    pub async fn get_music(
        &self,
        music_id: impl AsRef<str>,
        params: GetMusicParams,
    ) -> Result<Value> {
        let path = format!("/v1/tiktok/music/{music_id}", music_id = music_id.as_ref());
        let mut q = QueryParams::new();
        q.opt("region", params.region.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get music videos
    ///
    /// Get videos using a given TikTok sound.
    /// `GET /v1/tiktok/music/{music_id}/videos`
    pub async fn get_music_videos(
        &self,
        music_id: impl AsRef<str>,
        params: GetMusicVideosParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/tiktok/music/{music_id}/videos",
            music_id = music_id.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("region", params.region.as_ref());
        q.opt("count", params.count.as_ref());
        q.opt("cursor", params.cursor.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get oEmbed metadata
    ///
    /// Get cheap unauthenticated oEmbed metadata for a TikTok URL.
    /// `GET /v1/tiktok/oembed`
    pub async fn get_oembed(&self, params: GetOembedParams) -> Result<Value> {
        let path = "/v1/tiktok/oembed".to_string();
        let mut q = QueryParams::new();
        q.opt("url", params.url.as_ref());
        q.opt("region", params.region.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// List regions
    ///
    /// List supported TikTok content regions.
    /// `GET /v1/tiktok/regions`
    pub async fn list_regions(&self, params: ListRegionsParams) -> Result<Value> {
        let path = "/v1/tiktok/regions".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// General search
    ///
    /// General TikTok search — video results from the Top feed.
    /// `GET /v1/tiktok/search`
    pub async fn search_general(&self, params: SearchGeneralParams) -> Result<Value> {
        let path = "/v1/tiktok/search".to_string();
        let mut q = QueryParams::new();
        q.opt("query", params.query.as_ref());
        q.opt("region", params.region.as_ref());
        q.opt("count", params.count.as_ref());
        q.opt("cursor", params.cursor.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Search hashtags
    ///
    /// Search TikTok hashtags by keyword.
    /// `GET /v1/tiktok/search/hashtags`
    pub async fn search_hashtags(&self, params: SearchHashtagsParams) -> Result<Value> {
        let path = "/v1/tiktok/search/hashtags".to_string();
        let mut q = QueryParams::new();
        q.opt("query", params.query.as_ref());
        q.opt("region", params.region.as_ref());
        q.opt("count", params.count.as_ref());
        q.opt("cursor", params.cursor.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Search users
    ///
    /// Search TikTok users by keyword.
    /// `GET /v1/tiktok/search/users`
    pub async fn search_users(&self, params: SearchUsersParams) -> Result<Value> {
        let path = "/v1/tiktok/search/users".to_string();
        let mut q = QueryParams::new();
        q.opt("query", params.query.as_ref());
        q.opt("region", params.region.as_ref());
        q.opt("count", params.count.as_ref());
        q.opt("cursor", params.cursor.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Search videos
    ///
    /// Search TikTok videos by keyword.
    /// `GET /v1/tiktok/search/videos`
    pub async fn search_videos(&self, params: SearchVideosParams) -> Result<Value> {
        let path = "/v1/tiktok/search/videos".to_string();
        let mut q = QueryParams::new();
        q.opt("query", params.query.as_ref());
        q.opt("region", params.region.as_ref());
        q.opt("count", params.count.as_ref());
        q.opt("cursor", params.cursor.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Trending hashtags
    ///
    /// Get trending hashtags (mobile Discover surface — view_count + creators).
    /// `GET /v1/tiktok/trending/hashtags`
    pub async fn trending_hashtags(&self, params: TrendingHashtagsParams) -> Result<Value> {
        let path = "/v1/tiktok/trending/hashtags".to_string();
        let mut q = QueryParams::new();
        q.opt("region", params.region.as_ref());
        q.opt("period", params.period.as_ref());
        q.opt("count", params.count.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Trending songs
    ///
    /// Get trending songs/sounds (mobile hot-music feed — ranked by usage).
    /// `GET /v1/tiktok/trending/songs`
    pub async fn trending_songs(&self, params: TrendingSongsParams) -> Result<Value> {
        let path = "/v1/tiktok/trending/songs".to_string();
        let mut q = QueryParams::new();
        q.opt("region", params.region.as_ref());
        q.opt("period", params.period.as_ref());
        q.opt("count", params.count.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Trending videos
    ///
    /// Get trending videos from the TikTok Explore feed.
    /// `GET /v1/tiktok/trending/videos`
    pub async fn trending_videos(&self, params: TrendingVideosParams) -> Result<Value> {
        let path = "/v1/tiktok/trending/videos".to_string();
        let mut q = QueryParams::new();
        q.opt("region", params.region.as_ref());
        q.opt("count", params.count.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get user profile
    ///
    /// Get a TikTok user's full profile.
    /// `GET /v1/tiktok/users/{username}`
    pub async fn get_user(
        &self,
        username: impl AsRef<str>,
        params: GetUserParams,
    ) -> Result<Value> {
        let path = format!("/v1/tiktok/users/{username}", username = username.as_ref());
        let mut q = QueryParams::new();
        q.opt("region", params.region.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get followers (deprecated)
    ///
    /// DEPRECATED — TikTok followers require an authenticated account session. Returns HTTP 410.
    /// `GET /v1/tiktok/users/{username}/followers`
    pub async fn get_user_followers(
        &self,
        username: impl AsRef<str>,
        params: GetUserFollowersParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/tiktok/users/{username}/followers",
            username = username.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("region", params.region.as_ref());
        q.opt("count", params.count.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get following (deprecated)
    ///
    /// DEPRECATED — TikTok following requires an authenticated account session. Returns HTTP 410.
    /// `GET /v1/tiktok/users/{username}/following`
    pub async fn get_user_following(
        &self,
        username: impl AsRef<str>,
        params: GetUserFollowingParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/tiktok/users/{username}/following",
            username = username.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("region", params.region.as_ref());
        q.opt("count", params.count.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get liked videos (deprecated)
    ///
    /// DEPRECATED — TikTok liked videos require an authenticated account session. Returns HTTP 410.
    /// `GET /v1/tiktok/users/{username}/liked`
    pub async fn get_user_liked(
        &self,
        username: impl AsRef<str>,
        params: GetUserLikedParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/tiktok/users/{username}/liked",
            username = username.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("region", params.region.as_ref());
        q.opt("count", params.count.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get reposts
    ///
    /// Get videos a TikTok user has reposted.
    /// `GET /v1/tiktok/users/{username}/reposts`
    pub async fn get_user_reposts(
        &self,
        username: impl AsRef<str>,
        params: GetUserRepostsParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/tiktok/users/{username}/reposts",
            username = username.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("region", params.region.as_ref());
        q.opt("count", params.count.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get user videos
    ///
    /// Get a TikTok user's posted videos.
    /// `GET /v1/tiktok/users/{username}/videos`
    pub async fn get_user_videos(
        &self,
        username: impl AsRef<str>,
        params: GetUserVideosParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/tiktok/users/{username}/videos",
            username = username.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("region", params.region.as_ref());
        q.opt("count", params.count.as_ref());
        q.opt("cursor", params.cursor.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get video detail
    ///
    /// Get full metadata for a single TikTok video/post.
    /// `GET /v1/tiktok/videos/{video_id}`
    pub async fn get_video(
        &self,
        video_id: impl AsRef<str>,
        params: GetVideoParams,
    ) -> Result<Value> {
        let path = format!("/v1/tiktok/videos/{video_id}", video_id = video_id.as_ref());
        let mut q = QueryParams::new();
        q.opt("region", params.region.as_ref());
        q.opt("username", params.username.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get comments
    ///
    /// Get top-level comments on a TikTok video.
    /// `GET /v1/tiktok/videos/{video_id}/comments`
    pub async fn get_comments(
        &self,
        video_id: impl AsRef<str>,
        params: GetCommentsParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/tiktok/videos/{video_id}/comments",
            video_id = video_id.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("region", params.region.as_ref());
        q.opt("count", params.count.as_ref());
        q.opt("cursor", params.cursor.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get related videos
    ///
    /// Get TikTok's related videos for a given video.
    /// `GET /v1/tiktok/videos/{video_id}/related`
    pub async fn get_related(
        &self,
        video_id: impl AsRef<str>,
        params: GetRelatedParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/tiktok/videos/{video_id}/related",
            video_id = video_id.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("region", params.region.as_ref());
        q.opt("count", params.count.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get transcript
    ///
    /// Get subtitle/caption tracks for a TikTok video.
    /// `GET /v1/tiktok/videos/{video_id}/transcript`
    pub async fn get_transcript(
        &self,
        video_id: impl AsRef<str>,
        params: GetTranscriptParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/tiktok/videos/{video_id}/transcript",
            video_id = video_id.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("region", params.region.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }
}

// ===== Models =====

/// Parameters for [`SearchAdsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct SearchAdsParams {
    /// Keyword (ignored when advertiser_id is set)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    /// Advertiser business id(s) for advertiser search
    #[serde(skip_serializing_if = "Option::is_none")]
    pub advertiser_id: Option<String>,
    /// EU region code (the Ad Library is EU-only)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub days: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sort: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub offset: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub search_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
}

/// Parameters for [`GetCommentRepliesParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetCommentRepliesParams {
    /// Parent video id
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
    /// Pagination cursor from a prior page's pagination.cursor
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
}

/// Parameters for [`GetHashtagParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetHashtagParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
}

/// Parameters for [`GetHashtagVideosParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetHashtagVideosParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
    /// Pagination cursor from a prior page's pagination.cursor
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
}

/// Parameters for [`GetMusicParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetMusicParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
}

/// Parameters for [`GetMusicVideosParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetMusicVideosParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
    /// Pagination cursor from a prior page's pagination.cursor
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
}

/// Parameters for [`GetOembedParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetOembedParams {
    /// Full TikTok video or profile URL
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
}

/// Parameters for [`ListRegionsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ListRegionsParams {}

/// Parameters for [`SearchGeneralParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct SearchGeneralParams {
    /// Search keyword
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
    /// Composite pagination cursor (offset.search_id) from a prior page's pagination.cursor
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
}

/// Parameters for [`SearchHashtagsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct SearchHashtagsParams {
    /// Search keyword
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
    /// Composite pagination cursor (offset.search_id) from a prior page's pagination.cursor
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
}

/// Parameters for [`SearchUsersParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct SearchUsersParams {
    /// Search keyword
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
    /// Composite pagination cursor (offset.search_id) from a prior page's pagination.cursor
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
}

/// Parameters for [`SearchVideosParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct SearchVideosParams {
    /// Search keyword
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
    /// Composite pagination cursor (offset.search_id) from a prior page's pagination.cursor
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
}

/// Parameters for [`TrendingHashtagsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct TrendingHashtagsParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub period: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
}

/// Parameters for [`TrendingSongsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct TrendingSongsParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub period: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
}

/// Parameters for [`TrendingVideosParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct TrendingVideosParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
}

/// Parameters for [`GetUserParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetUserParams {
    /// Content region (ISO 3166-1 alpha-2)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
}

/// Parameters for [`GetUserFollowersParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetUserFollowersParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
}

/// Parameters for [`GetUserFollowingParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetUserFollowingParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
}

/// Parameters for [`GetUserLikedParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetUserLikedParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
}

/// Parameters for [`GetUserRepostsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetUserRepostsParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
}

/// Parameters for [`GetUserVideosParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetUserVideosParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
    /// Pagination cursor from a prior page's `pagination.cursor` (signer path only).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
}

/// Parameters for [`GetVideoParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetVideoParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    /// Author handle (skips oEmbed lookup)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
}

/// Parameters for [`GetCommentsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetCommentsParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
    /// Pagination cursor from a prior page's pagination.cursor
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
}

/// Parameters for [`GetRelatedParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetRelatedParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
}

/// Parameters for [`GetTranscriptParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetTranscriptParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
}
