// @generated by `cargo run -p xtask -- gen` from specs/depop.json — do not edit by hand.
#![allow(clippy::all)]
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    non_snake_case,
    rustdoc::all
)]

use crate::core::{Client, Error, Method, QueryParams, Result};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;

/// Handle for the `depop` platform. Obtain via [`crate::ScrapeBadger::depop`].
#[derive(Clone)]
pub struct Depop {
    client: Client,
}

impl Depop {
    pub(crate) fn new(client: Client) -> Self {
        Self { client }
    }

    /// Access the underlying transport client.
    pub fn client(&self) -> &Client {
        &self.client
    }

    /// List markets
    ///
    /// List supported Depop markets (country + currency).
    /// `GET /v1/depop/markets`
    pub async fn list_markets(&self, params: ListMarketsParams) -> Result<Value> {
        let path = "/v1/depop/markets".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get product detail
    ///
    /// Full detail for a single product (by numeric id or slug).
    /// `GET /v1/depop/products/{product_id}`
    pub async fn get_product(
        &self,
        product_id: impl AsRef<str>,
        params: GetProductParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/depop/products/{product_id}",
            product_id = product_id.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("market", params.market.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Search Depop products
    ///
    /// Search the Depop catalog with filters (cursor-paginated).
    /// `GET /v1/depop/search`
    pub async fn search(&self, params: SearchParams) -> Result<Value> {
        let path = "/v1/depop/search".to_string();
        let mut q = QueryParams::new();
        q.opt("query", params.query.as_ref());
        q.opt("market", params.market.as_ref());
        q.opt("per_page", params.per_page.as_ref());
        q.opt("cursor", params.cursor.as_ref());
        q.opt("price_min", params.price_min.as_ref());
        q.opt("price_max", params.price_max.as_ref());
        q.opt("brands", params.brands.as_ref());
        q.opt("categories", params.categories.as_ref());
        q.opt("sizes", params.sizes.as_ref());
        q.opt("conditions", params.conditions.as_ref());
        q.opt("gender", params.gender.as_ref());
        q.opt("sort", params.sort.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get shop/user profile
    ///
    /// Public shop/user profile by username.
    /// `GET /v1/depop/users/{username}`
    pub async fn get_user(
        &self,
        username: impl AsRef<str>,
        params: GetUserParams,
    ) -> Result<Value> {
        let path = format!("/v1/depop/users/{username}", username = username.as_ref());
        let mut q = QueryParams::new();
        q.opt("market", params.market.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get a user's products
    ///
    /// A user's active listings (cursor-paginated).
    /// `GET /v1/depop/users/{username}/products`
    pub async fn get_user_products(
        &self,
        username: impl AsRef<str>,
        params: GetUserProductsParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/depop/users/{username}/products",
            username = username.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("market", params.market.as_ref());
        q.opt("per_page", params.per_page.as_ref());
        q.opt("cursor", params.cursor.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }
}

// ===== Models =====

/// Parameters for [`ListMarketsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ListMarketsParams {}

/// Parameters for [`GetProductParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetProductParams {
    /// Market code
    #[serde(skip_serializing_if = "Option::is_none")]
    pub market: Option<String>,
}

/// Parameters for [`SearchParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct SearchParams {
    /// Search text, e.g. 'nike vintage'
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    /// Market code (us, gb, au, it, fr, ...)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub market: Option<String>,
    /// Results per page
    #[serde(skip_serializing_if = "Option::is_none")]
    pub per_page: Option<i64>,
    /// Pagination cursor (from previous page)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// Minimum price
    #[serde(skip_serializing_if = "Option::is_none")]
    pub price_min: Option<f64>,
    /// Maximum price
    #[serde(skip_serializing_if = "Option::is_none")]
    pub price_max: Option<f64>,
    /// Comma-separated brand IDs
    #[serde(skip_serializing_if = "Option::is_none")]
    pub brands: Option<String>,
    /// Comma-separated category IDs
    #[serde(skip_serializing_if = "Option::is_none")]
    pub categories: Option<String>,
    /// Comma-separated size IDs
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sizes: Option<String>,
    /// Comma-separated condition slugs (brand_new, used_excellent, ...)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub conditions: Option<String>,
    /// male | female
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gender: Option<String>,
    /// relevance | newlyListed | priceAscending | priceDescending
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sort: Option<String>,
}

/// Parameters for [`GetUserParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetUserParams {
    /// Market code
    #[serde(skip_serializing_if = "Option::is_none")]
    pub market: Option<String>,
}

/// Parameters for [`GetUserProductsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetUserProductsParams {
    /// Market code
    #[serde(skip_serializing_if = "Option::is_none")]
    pub market: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub per_page: Option<i64>,
    /// Pagination cursor
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
}
