// @generated by `cargo run -p xtask -- gen` from specs/google.json — do not edit by hand.
#![allow(clippy::all)]
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    non_snake_case,
    rustdoc::all
)]

use crate::core::{Client, Error, Method, QueryParams, Result};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;

/// Handle for the `google` platform. Obtain via [`crate::ScrapeBadger::google`].
#[derive(Clone)]
pub struct Google {
    client: Client,
}

impl Google {
    pub(crate) fn new(client: Client) -> Self {
        Self { client }
    }

    /// Access the underlying transport client.
    pub fn client(&self) -> &Client {
        &self.client
    }

    /// Google AI Mode search
    ///
    /// Get AI-generated search results from Google AI Mode.
    ///
    /// Returns the structured `text_blocks` (paragraphs, headings, comparison
    /// `table` blocks and lists), a flat `references` source list, a compact
    /// `markdown` rendering of the whole answer and — unless `include_html`
    /// is false — the raw `answer_html` body.
    /// `GET /v1/google/ai-mode/search`
    pub async fn ai_mode_search(&self, params: AiModeSearchParams) -> Result<Value> {
        let path = "/v1/google/ai-mode/search".to_string();
        let mut q = QueryParams::new();
        q.opt("q", params.q.as_ref());
        q.opt("gl", params.gl.as_ref());
        q.opt("hl", params.hl.as_ref());
        q.opt("include_html", params.include_html.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Google AI Overview (inline SERP block)
    ///
    /// Get the AI Overview block Google renders inline at the top of a SERP.
    ///
    /// Deferred overviews (where Google lazy-loads the block via a follow-up
    /// ``page_token``) are chased automatically.
    /// `GET /v1/google/ai-overview`
    pub async fn ai_overview(&self, params: AiOverviewParams) -> Result<Value> {
        let path = "/v1/google/ai-overview".to_string();
        let mut q = QueryParams::new();
        q.opt("q", params.q.as_ref());
        q.opt("gl", params.gl.as_ref());
        q.opt("hl", params.hl.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Google search suggestions
    ///
    /// Get Google search autocomplete suggestions.
    /// `GET /v1/google/autocomplete`
    pub async fn autocomplete(&self, params: AutocompleteParams) -> Result<Value> {
        let path = "/v1/google/autocomplete".to_string();
        let mut q = QueryParams::new();
        q.opt("q", params.q.as_ref());
        q.opt("hl", params.hl.as_ref());
        q.opt("gl", params.gl.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get stock/index quote
    ///
    /// Get a stock or index quote from Google Finance.
    /// `GET /v1/google/finance/quote`
    pub async fn finance_quote(&self, params: FinanceQuoteParams) -> Result<Value> {
        let path = "/v1/google/finance/quote".to_string();
        let mut q = QueryParams::new();
        q.opt("q", params.q.as_ref());
        q.opt("hl", params.hl.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Google Flights search
    ///
    /// Search Google Flights for available itineraries.
    /// `GET /v1/google/flights/search`
    pub async fn flights_search(&self, params: FlightsSearchParams) -> Result<Value> {
        let path = "/v1/google/flights/search".to_string();
        let mut q = QueryParams::new();
        q.opt("departure_id", params.departure_id.as_ref());
        q.opt("arrival_id", params.arrival_id.as_ref());
        q.opt("outbound_date", params.outbound_date.as_ref());
        q.opt("return_date", params.return_date.as_ref());
        q.opt("trip_type", params.trip_type.as_ref());
        q.opt("adults", params.adults.as_ref());
        q.opt("children", params.children.as_ref());
        q.opt("infants_in_seat", params.infants_in_seat.as_ref());
        q.opt("infants_on_lap", params.infants_on_lap.as_ref());
        q.opt("travel_class", params.travel_class.as_ref());
        q.opt("currency", params.currency.as_ref());
        q.opt("gl", params.gl.as_ref());
        q.opt("hl", params.hl.as_ref());
        q.opt("stops", params.stops.as_ref());
        q.opt("max_price", params.max_price.as_ref());
        q.opt("departure_token", params.departure_token.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Hotel details
    /// `GET /v1/google/hotels/details`
    pub async fn hotel_details(&self, params: HotelDetailsParams) -> Result<Value> {
        let path = "/v1/google/hotels/details".to_string();
        let mut q = QueryParams::new();
        q.opt("property_token", params.property_token.as_ref());
        q.opt("check_in", params.check_in.as_ref());
        q.opt("check_out", params.check_out.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Search hotels
    /// `GET /v1/google/hotels/search`
    pub async fn hotels_search(&self, params: HotelsSearchParams) -> Result<Value> {
        let path = "/v1/google/hotels/search".to_string();
        let mut q = QueryParams::new();
        q.opt("q", params.q.as_ref());
        q.opt("check_in", params.check_in.as_ref());
        q.opt("check_out", params.check_out.as_ref());
        q.opt("adults", params.adults.as_ref());
        q.opt("currency", params.currency.as_ref());
        q.opt("gl", params.gl.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Search Google Images
    ///
    /// Search Google Images for visual content.
    /// `GET /v1/google/images/search`
    pub async fn images_search(&self, params: ImagesSearchParams) -> Result<Value> {
        let path = "/v1/google/images/search".to_string();
        let mut q = QueryParams::new();
        q.opt("q", params.q.as_ref());
        q.opt("gl", params.gl.as_ref());
        q.opt("hl", params.hl.as_ref());
        q.opt("tbs", params.tbs.as_ref());
        q.opt("imgsz", params.imgsz.as_ref());
        q.opt("imgcolor", params.imgcolor.as_ref());
        q.opt("imgtype", params.imgtype.as_ref());
        q.opt("safe", params.safe.as_ref());
        q.opt("page", params.page.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Search Google Jobs
    /// `GET /v1/google/jobs/search`
    pub async fn jobs_search(&self, params: JobsSearchParams) -> Result<Value> {
        let path = "/v1/google/jobs/search".to_string();
        let mut q = QueryParams::new();
        q.opt("q", params.q.as_ref());
        q.opt("location", params.location.as_ref());
        q.opt("gl", params.gl.as_ref());
        q.opt("job_type", params.job_type.as_ref());
        q.opt("date_posted", params.date_posted.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Google Lens visual search
    ///
    /// Google Lens visual search.
    ///
    /// Response carries ``lens_results`` (Scrapingdog parity alias) with
    /// ``title`` / ``source`` / ``source_favicon`` / ``thumbnail`` / ``tag``
    /// (price chip) / ``in_stock``, plus ``related_searches`` chips.
    /// Legacy ``results`` alias kept for backwards compat.
    /// `GET /v1/google/lens/search`
    pub async fn lens_search(&self, params: LensSearchParams) -> Result<Value> {
        let path = "/v1/google/lens/search".to_string();
        let mut q = QueryParams::new();
        q.opt("url", params.url.as_ref());
        q.opt("query", params.query.as_ref());
        q.opt("country", params.country.as_ref());
        q.opt("language", params.language.as_ref());
        q.opt("gl", params.gl.as_ref());
        q.opt("hl", params.hl.as_ref());
        q.opt("product", params.product.as_ref());
        q.opt("visual_matches", params.visual_matches.as_ref());
        q.opt("exact_matches", params.exact_matches.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get place photos
    /// `GET /v1/google/maps/photos`
    pub async fn maps_photos(&self, params: MapsPhotosParams) -> Result<Value> {
        let path = "/v1/google/maps/photos".to_string();
        let mut q = QueryParams::new();
        q.opt("data_id", params.data_id.as_ref());
        q.opt("hl", params.hl.as_ref());
        q.opt("next_page_token", params.next_page_token.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get place details
    /// `GET /v1/google/maps/place`
    pub async fn maps_place(&self, params: MapsPlaceParams) -> Result<Value> {
        let path = "/v1/google/maps/place".to_string();
        let mut q = QueryParams::new();
        q.opt("place_id", params.place_id.as_ref());
        q.opt("data_id", params.data_id.as_ref());
        q.opt("hl", params.hl.as_ref());
        q.opt("gl", params.gl.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get business posts
    /// `GET /v1/google/maps/posts`
    pub async fn maps_posts(&self, params: MapsPostsParams) -> Result<Value> {
        let path = "/v1/google/maps/posts".to_string();
        let mut q = QueryParams::new();
        q.opt("data_id", params.data_id.as_ref());
        q.opt("next_page_token", params.next_page_token.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get place reviews
    /// `GET /v1/google/maps/reviews`
    pub async fn maps_reviews(&self, params: MapsReviewsParams) -> Result<Value> {
        let path = "/v1/google/maps/reviews".to_string();
        let mut q = QueryParams::new();
        q.opt("data_id", params.data_id.as_ref());
        q.opt("sort_by", params.sort_by.as_ref());
        q.opt("hl", params.hl.as_ref());
        q.opt("next_page_token", params.next_page_token.as_ref());
        q.opt("results", params.results.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Search Google Maps places
    /// `GET /v1/google/maps/search`
    pub async fn maps_search(&self, params: MapsSearchParams) -> Result<Value> {
        let path = "/v1/google/maps/search".to_string();
        let mut q = QueryParams::new();
        q.opt("q", params.q.as_ref());
        q.opt("ll", params.ll.as_ref());
        q.opt("gl", params.gl.as_ref());
        q.opt("hl", params.hl.as_ref());
        q.opt("start", params.start.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Search Google News
    /// `GET /v1/google/news/search`
    pub async fn news_search(&self, params: NewsSearchParams) -> Result<Value> {
        let path = "/v1/google/news/search".to_string();
        let mut q = QueryParams::new();
        q.opt("q", params.q.as_ref());
        q.opt("hl", params.hl.as_ref());
        q.opt("gl", params.gl.as_ref());
        q.opt("max_results", params.max_results.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// News by topic
    /// `GET /v1/google/news/topics`
    pub async fn news_topics(&self, params: NewsTopicsParams) -> Result<Value> {
        let path = "/v1/google/news/topics".to_string();
        let mut q = QueryParams::new();
        q.opt("topic", params.topic.as_ref());
        q.opt("hl", params.hl.as_ref());
        q.opt("gl", params.gl.as_ref());
        q.opt("max_results", params.max_results.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Trending news
    /// `GET /v1/google/news/trending`
    pub async fn news_trending(&self, params: NewsTrendingParams) -> Result<Value> {
        let path = "/v1/google/news/trending".to_string();
        let mut q = QueryParams::new();
        q.opt("hl", params.hl.as_ref());
        q.opt("gl", params.gl.as_ref());
        q.opt("max_results", params.max_results.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Patent details
    /// `GET /v1/google/patents/detail`
    pub async fn patent_detail(&self, params: PatentDetailParams) -> Result<Value> {
        let path = "/v1/google/patents/detail".to_string();
        let mut q = QueryParams::new();
        q.opt("patent_id", params.patent_id.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Search patents
    /// `GET /v1/google/patents/search`
    pub async fn patents_search(&self, params: PatentsSearchParams) -> Result<Value> {
        let path = "/v1/google/patents/search".to_string();
        let mut q = QueryParams::new();
        q.opt("q", params.q.as_ref());
        q.opt("page", params.page.as_ref());
        q.opt("num", params.num.as_ref());
        q.opt("sort", params.sort.as_ref());
        q.opt("inventor", params.inventor.as_ref());
        q.opt("assignee", params.assignee.as_ref());
        q.opt("country", params.country.as_ref());
        q.opt("language", params.language.as_ref());
        q.opt("status", params.status.as_ref());
        q.opt("patent_type", params.patent_type.as_ref());
        q.opt("before", params.before.as_ref());
        q.opt("after", params.after.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Immersive product detail
    ///
    /// Get deep product details from Google's immersive product page.
    /// `GET /v1/google/products/detail`
    pub async fn products_detail(&self, params: ProductsDetailParams) -> Result<Value> {
        let path = "/v1/google/products/detail".to_string();
        let mut q = QueryParams::new();
        q.opt("product_id", params.product_id.as_ref());
        q.opt("q", params.q.as_ref());
        q.opt("gl", params.gl.as_ref());
        q.opt("hl", params.hl.as_ref());
        q.opt("catalog_id", params.catalog_id.as_ref());
        q.opt("image_docid", params.image_docid.as_ref());
        q.opt("headline_offer_docid", params.headline_offer_docid.as_ref());
        q.opt("mid", params.mid.as_ref());
        q.opt("include_offers", params.include_offers.as_ref());
        q.opt("include_variants", params.include_variants.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get Scholar author profile
    ///
    /// Get detailed Google Scholar author profile including articles, stats, co-authors.
    /// `GET /v1/google/scholar/author`
    pub async fn scholar_author(&self, params: ScholarAuthorParams) -> Result<Value> {
        let path = "/v1/google/scholar/author".to_string();
        let mut q = QueryParams::new();
        q.opt("author_id", params.author_id.as_ref());
        q.opt("hl", params.hl.as_ref());
        q.opt("cstart", params.cstart.as_ref());
        q.opt("pagesize", params.pagesize.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get author citations-per-year chart
    ///
    /// Return the citations-per-year chart for a Google Scholar author.
    /// `GET /v1/google/scholar/author/citation`
    pub async fn scholar_author_citation(
        &self,
        params: ScholarAuthorCitationParams,
    ) -> Result<Value> {
        let path = "/v1/google/scholar/author/citation".to_string();
        let mut q = QueryParams::new();
        q.opt("author_id", params.author_id.as_ref());
        q.opt("hl", params.hl.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get citation formats for a Scholar paper
    ///
    /// Return MLA, APA, Chicago, Harvard, and Vancouver citation formats for a paper.
    /// `GET /v1/google/scholar/cite`
    pub async fn scholar_cite(&self, params: ScholarCiteParams) -> Result<Value> {
        let path = "/v1/google/scholar/cite".to_string();
        let mut q = QueryParams::new();
        q.opt("q", params.q.as_ref());
        q.opt("hl", params.hl.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Search Scholar author profiles
    ///
    /// Search Google Scholar for author profiles by name.
    /// `GET /v1/google/scholar/profiles`
    pub async fn scholar_profiles(&self, params: ScholarProfilesParams) -> Result<Value> {
        let path = "/v1/google/scholar/profiles".to_string();
        let mut q = QueryParams::new();
        q.opt("mauthors", params.mauthors.as_ref());
        q.opt("hl", params.hl.as_ref());
        q.opt("after_author", params.after_author.as_ref());
        q.opt("before_author", params.before_author.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Search Google Scholar
    ///
    /// Search Google Scholar for scholarly articles.
    ///
    /// Each result ships with its doc ``id``, ``type`` badge
    /// ([BOOK]/[PDF]/...), wrapped ``inline_links`` (versions + cited_by +
    /// related), PDF ``resources`` list, and structured ``authors`` (with
    /// ``author_id`` for profiled authors — pipe straight into
    /// ``/scholar/author``). Envelope carries ``scholar_results`` alias
    /// (Scrapingdog parity), ``related_searches``, and matched
    /// `GET /v1/google/scholar/search`
    pub async fn scholar_search(&self, params: ScholarSearchParams) -> Result<Value> {
        let path = "/v1/google/scholar/search".to_string();
        let mut q = QueryParams::new();
        q.opt("q", params.q.as_ref());
        q.opt("hl", params.hl.as_ref());
        q.opt("as_ylo", params.as_ylo.as_ref());
        q.opt("as_yhi", params.as_yhi.as_ref());
        q.opt("as_sdt", params.as_sdt.as_ref());
        q.opt("page", params.page.as_ref());
        q.opt("num", params.num.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Google web search
    ///
    /// Search Google and get structured results (organic, ads, KG, AI overview, PAA).
    /// `GET /v1/google/search`
    pub async fn search(&self, params: SearchParams) -> Result<Value> {
        let path = "/v1/google/search".to_string();
        let mut q = QueryParams::new();
        q.opt("q", params.q.as_ref());
        q.opt("gl", params.gl.as_ref());
        q.opt("hl", params.hl.as_ref());
        q.opt("num", params.num.as_ref());
        q.opt("start", params.start.as_ref());
        q.opt("domain", params.domain.as_ref());
        q.opt("device", params.device.as_ref());
        q.opt("user_agent", params.user_agent.as_ref());
        q.opt("output", params.output.as_ref());
        q.opt("location", params.location.as_ref());
        q.opt("lr", params.lr.as_ref());
        q.opt("tbs", params.tbs.as_ref());
        q.opt("safe", params.safe.as_ref());
        q.opt("uule", params.uule.as_ref());
        q.opt("filter", params.filter.as_ref());
        q.opt("nfpr", params.nfpr.as_ref());
        q.opt("cr", params.cr.as_ref());
        q.opt("ludocid", params.ludocid.as_ref());
        q.opt("lsig", params.lsig.as_ref());
        q.opt("kgmid", params.kgmid.as_ref());
        q.opt("si", params.si.as_ref());
        q.opt("ibp", params.ibp.as_ref());
        q.opt("uds", params.uds.as_ref());
        q.opt("ai_overview", params.ai_overview.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Search products
    /// `GET /v1/google/shopping/search`
    pub async fn shopping_search(&self, params: ShoppingSearchParams) -> Result<Value> {
        let path = "/v1/google/shopping/search".to_string();
        let mut q = QueryParams::new();
        q.opt("q", params.q.as_ref());
        q.opt("gl", params.gl.as_ref());
        q.opt("min_price", params.min_price.as_ref());
        q.opt("max_price", params.max_price.as_ref());
        q.opt("sort_by", params.sort_by.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Google Shorts search
    ///
    /// Return short-form video results (YouTube Shorts, TikToks) from Google Shorts mode.
    /// `GET /v1/google/shorts/search`
    pub async fn shorts_search(&self, params: ShortsSearchParams) -> Result<Value> {
        let path = "/v1/google/shorts/search".to_string();
        let mut q = QueryParams::new();
        q.opt("q", params.q.as_ref());
        q.opt("gl", params.gl.as_ref());
        q.opt("hl", params.hl.as_ref());
        q.opt("domain", params.domain.as_ref());
        q.opt("num", params.num.as_ref());
        q.opt("start", params.start.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Trends topic autocomplete
    ///
    /// Return categorized Knowledge Graph topic entities (mid, type) for a query.
    /// `GET /v1/google/trends/autocomplete`
    pub async fn trends_autocomplete(&self, params: TrendsAutocompleteParams) -> Result<Value> {
        let path = "/v1/google/trends/autocomplete".to_string();
        let mut q = QueryParams::new();
        q.opt("q", params.q.as_ref());
        q.opt("hl", params.hl.as_ref());
        q.opt("tz", params.tz.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Interest over time
    /// `GET /v1/google/trends/interest`
    pub async fn trends_interest(&self, params: TrendsInterestParams) -> Result<Value> {
        let path = "/v1/google/trends/interest".to_string();
        let mut q = QueryParams::new();
        q.opt("q", params.q.as_ref());
        q.opt("geo", params.geo.as_ref());
        q.opt("date", params.date.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Interest by region
    /// `GET /v1/google/trends/regions`
    pub async fn trends_regions(&self, params: TrendsRegionsParams) -> Result<Value> {
        let path = "/v1/google/trends/regions".to_string();
        let mut q = QueryParams::new();
        q.opt("q", params.q.as_ref());
        q.opt("geo", params.geo.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Related topics & queries
    /// `GET /v1/google/trends/related`
    pub async fn trends_related(&self, params: TrendsRelatedParams) -> Result<Value> {
        let path = "/v1/google/trends/related".to_string();
        let mut q = QueryParams::new();
        q.opt("q", params.q.as_ref());
        q.opt("geo", params.geo.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Trending searches
    /// `GET /v1/google/trends/trending`
    pub async fn trends_trending(&self, params: TrendsTrendingParams) -> Result<Value> {
        let path = "/v1/google/trends/trending".to_string();
        let mut q = QueryParams::new();
        q.opt("geo", params.geo.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Search Google Videos
    ///
    /// Search Google for video results.
    /// `GET /v1/google/videos/search`
    pub async fn videos_search(&self, params: VideosSearchParams) -> Result<Value> {
        let path = "/v1/google/videos/search".to_string();
        let mut q = QueryParams::new();
        q.opt("q", params.q.as_ref());
        q.opt("gl", params.gl.as_ref());
        q.opt("hl", params.hl.as_ref());
        q.opt("tbs", params.tbs.as_ref());
        q.opt("safe", params.safe.as_ref());
        q.opt("page", params.page.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }
}

// ===== Models =====

/// Device target: desktop, mobile, iphone, android, tablet
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum SearchDevice {
    /// `desktop`
    #[serde(rename = "desktop")]
    Desktop,
    /// `mobile`
    #[serde(rename = "mobile")]
    Mobile,
    /// `iphone`
    #[serde(rename = "iphone")]
    Iphone,
    /// `android`
    #[serde(rename = "android")]
    Android,
    /// `tablet`
    #[serde(rename = "tablet")]
    Tablet,
}

impl std::fmt::Display for SearchDevice {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            SearchDevice::Desktop => "desktop",
            SearchDevice::Mobile => "mobile",
            SearchDevice::Iphone => "iphone",
            SearchDevice::Android => "android",
            SearchDevice::Tablet => "tablet",
        })
    }
}

/// Response format: json (parsed) or html (raw SERP)
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum SearchOutput {
    /// `json`
    #[serde(rename = "json")]
    Json,
    /// `html`
    #[serde(rename = "html")]
    Html,
}

impl std::fmt::Display for SearchOutput {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            SearchOutput::Json => "json",
            SearchOutput::Html => "html",
        })
    }
}

/// Parameters for [`AiModeSearchParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct AiModeSearchParams {
    /// Search query for AI-generated response
    #[serde(skip_serializing_if = "Option::is_none")]
    pub q: Option<String>,
    /// Country code
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gl: Option<String>,
    /// Language code
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hl: Option<String>,
    /// Include the raw `answer_html` (full answer body HTML) in the response for maximum parity. It can be 100s of KB — set false when you only need the structured `text_blocks` + `markdown`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub include_html: Option<bool>,
}

/// Parameters for [`AiOverviewParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct AiOverviewParams {
    /// Search query — same shape as a Google Search query
    #[serde(skip_serializing_if = "Option::is_none")]
    pub q: Option<String>,
    /// Country code
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gl: Option<String>,
    /// Language code
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hl: Option<String>,
}

/// Parameters for [`AutocompleteParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct AutocompleteParams {
    /// Search query to get suggestions for
    #[serde(skip_serializing_if = "Option::is_none")]
    pub q: Option<String>,
    /// Language code
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hl: Option<String>,
    /// Country code
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gl: Option<String>,
}

/// Parameters for [`FinanceQuoteParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct FinanceQuoteParams {
    /// Ticker and exchange (e.g. "AAPL:NASDAQ", "BTC-USD")
    #[serde(skip_serializing_if = "Option::is_none")]
    pub q: Option<String>,
    /// Language code
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hl: Option<String>,
}

/// Parameters for [`FlightsSearchParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct FlightsSearchParams {
    /// Departure airport IATA code or location ID
    #[serde(skip_serializing_if = "Option::is_none")]
    pub departure_id: Option<String>,
    /// Arrival airport IATA code or location ID
    #[serde(skip_serializing_if = "Option::is_none")]
    pub arrival_id: Option<String>,
    /// Outbound date (YYYY-MM-DD)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub outbound_date: Option<String>,
    /// Return date (round-trip only)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub return_date: Option<String>,
    /// round_trip | one_way | multi_city
    #[serde(skip_serializing_if = "Option::is_none")]
    pub trip_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub adults: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub children: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub infants_in_seat: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub infants_on_lap: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub travel_class: Option<String>,
    /// ISO-4217 currency
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gl: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hl: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stops: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_price: Option<i64>,
    /// A round-trip offer's departure_token; returns the return-leg flights for that selected outbound (round-trip only).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub departure_token: Option<String>,
}

/// Parameters for [`HotelDetailsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct HotelDetailsParams {
    /// Property token
    #[serde(skip_serializing_if = "Option::is_none")]
    pub property_token: Option<String>,
    /// YYYY-MM-DD
    #[serde(skip_serializing_if = "Option::is_none")]
    pub check_in: Option<String>,
    /// YYYY-MM-DD
    #[serde(skip_serializing_if = "Option::is_none")]
    pub check_out: Option<String>,
}

/// Parameters for [`HotelsSearchParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct HotelsSearchParams {
    /// Location or hotel name
    #[serde(skip_serializing_if = "Option::is_none")]
    pub q: Option<String>,
    /// YYYY-MM-DD
    #[serde(skip_serializing_if = "Option::is_none")]
    pub check_in: Option<String>,
    /// YYYY-MM-DD
    #[serde(skip_serializing_if = "Option::is_none")]
    pub check_out: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub adults: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gl: Option<String>,
}

/// Parameters for [`ImagesSearchParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ImagesSearchParams {
    /// Image search query
    #[serde(skip_serializing_if = "Option::is_none")]
    pub q: Option<String>,
    /// Country code
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gl: Option<String>,
    /// Language code
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hl: Option<String>,
    /// Time/filter string (e.g. qdr:d)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tbs: Option<String>,
    /// Image size: l, m, i, xXl
    #[serde(skip_serializing_if = "Option::is_none")]
    pub imgsz: Option<String>,
    /// Image color filter
    #[serde(skip_serializing_if = "Option::is_none")]
    pub imgcolor: Option<String>,
    /// Image type: face, photo, clipart
    #[serde(skip_serializing_if = "Option::is_none")]
    pub imgtype: Option<String>,
    /// Safe search
    #[serde(skip_serializing_if = "Option::is_none")]
    pub safe: Option<String>,
    /// Page number
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
}

/// Parameters for [`JobsSearchParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct JobsSearchParams {
    /// Job title, keywords
    #[serde(skip_serializing_if = "Option::is_none")]
    pub q: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gl: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub job_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub date_posted: Option<String>,
}

/// Parameters for [`LensSearchParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct LensSearchParams {
    /// Public URL of the image to search visually
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Optional text refinement (e.g. 'pizza')
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    /// ISO country code (alias for gl)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// Language code (alias for hl)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    /// Country code
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gl: Option<String>,
    /// Language code
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hl: Option<String>,
    /// Bias towards shoppable product matches
    #[serde(skip_serializing_if = "Option::is_none")]
    pub product: Option<bool>,
    /// Include the visual-matches carousel
    #[serde(skip_serializing_if = "Option::is_none")]
    pub visual_matches: Option<bool>,
    /// Restrict to exact-match results
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exact_matches: Option<bool>,
}

/// Parameters for [`MapsPhotosParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct MapsPhotosParams {
    /// Maps data ID
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hl: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
}

/// Parameters for [`MapsPlaceParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct MapsPlaceParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub place_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hl: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gl: Option<String>,
}

/// Parameters for [`MapsPostsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct MapsPostsParams {
    /// Maps data ID
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
}

/// Parameters for [`MapsReviewsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct MapsReviewsParams {
    /// Maps data ID
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sort_by: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hl: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub results: Option<i64>,
}

/// Parameters for [`MapsSearchParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct MapsSearchParams {
    /// Search query
    #[serde(skip_serializing_if = "Option::is_none")]
    pub q: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ll: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gl: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hl: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub start: Option<i64>,
}

/// Parameters for [`NewsSearchParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct NewsSearchParams {
    /// Search query
    #[serde(skip_serializing_if = "Option::is_none")]
    pub q: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hl: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gl: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_results: Option<i64>,
}

/// Parameters for [`NewsTopicsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct NewsTopicsParams {
    /// Topic name
    #[serde(skip_serializing_if = "Option::is_none")]
    pub topic: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hl: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gl: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_results: Option<i64>,
}

/// Parameters for [`NewsTrendingParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct NewsTrendingParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hl: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gl: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_results: Option<i64>,
}

/// Parameters for [`PatentDetailParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct PatentDetailParams {
    /// Patent number
    #[serde(skip_serializing_if = "Option::is_none")]
    pub patent_id: Option<String>,
}

/// Parameters for [`PatentsSearchParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct PatentsSearchParams {
    /// Search query (Boolean logic supported)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub q: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub num: Option<i64>,
    /// 'new' or 'old'
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sort: Option<String>,
    /// Inventor name(s)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inventor: Option<String>,
    /// Assignee / company name(s)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub assignee: Option<String>,
    /// Country code (US, EP, WO, …)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// Patent language: ENGLISH, GERMAN, CHINESE, FRENCH, JAPANESE, KOREAN, SPANISH
    #[serde(skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    /// GRANT or APPLICATION
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// PATENT or DESIGN
    #[serde(skip_serializing_if = "Option::is_none")]
    pub patent_type: Option<String>,
    /// Before date YYYYMMDD
    #[serde(skip_serializing_if = "Option::is_none")]
    pub before: Option<String>,
    /// After date YYYYMMDD
    #[serde(skip_serializing_if = "Option::is_none")]
    pub after: Option<String>,
}

/// Parameters for [`ProductsDetailParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ProductsDetailParams {
    /// Google Shopping ``gpcid`` — the product_id returned on ``/shopping/search`` tiles. Scrapingdog-compatible.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub product_id: Option<String>,
    /// Original search query that surfaced the product. Required by Google's ``/async/oapv`` RPC.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub q: Option<String>,
    /// Country code (ISO 3166 alpha-2)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gl: Option<String>,
    /// Language code
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hl: Option<String>,
    /// Optional ``catalogid`` from the Shopping tile (improves parity).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub catalog_id: Option<String>,
    /// Optional ``imageDocid`` for higher-fidelity images.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub image_docid: Option<String>,
    /// Optional ``headlineOfferDocid`` to pin the featured seller.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub headline_offer_docid: Option<String>,
    /// Optional Google Knowledge-Graph ``mid``.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mid: Option<String>,
    /// When true, fetch the full merchant-offer list via a secondary RPC (``/async/piu_ps``). Adds ~1 s.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub include_offers: Option<bool>,
    /// When true, fetch size/colour variants via a secondary RPC (``/async/toy_v``). Adds ~1 s.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub include_variants: Option<bool>,
}

/// Parameters for [`ScholarAuthorParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ScholarAuthorParams {
    /// Scholar user ID (the `user` query parameter)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub author_id: Option<String>,
    /// Language code
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hl: Option<String>,
    /// Articles pagination offset
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cstart: Option<i64>,
    /// Articles per page
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pagesize: Option<i64>,
}

/// Parameters for [`ScholarAuthorCitationParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ScholarAuthorCitationParams {
    /// Scholar user ID
    #[serde(skip_serializing_if = "Option::is_none")]
    pub author_id: Option<String>,
    /// Language code
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hl: Option<String>,
}

/// Parameters for [`ScholarCiteParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ScholarCiteParams {
    /// Cluster ID from a search result
    #[serde(skip_serializing_if = "Option::is_none")]
    pub q: Option<String>,
    /// Language code
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hl: Option<String>,
}

/// Parameters for [`ScholarProfilesParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ScholarProfilesParams {
    /// Author name query (e.g. 'Geoffrey Hinton')
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mauthors: Option<String>,
    /// Language code
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hl: Option<String>,
    /// Pagination token (next page)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub after_author: Option<String>,
    /// Pagination token (previous page)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub before_author: Option<String>,
}

/// Parameters for [`ScholarSearchParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ScholarSearchParams {
    /// Search query for scholarly articles
    #[serde(skip_serializing_if = "Option::is_none")]
    pub q: Option<String>,
    /// Language code
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hl: Option<String>,
    /// Year from (e.g. 2020)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub as_ylo: Option<i64>,
    /// Year to (e.g. 2024)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub as_yhi: Option<i64>,
    /// Search type: 0=exclude patents, 7=include
    #[serde(skip_serializing_if = "Option::is_none")]
    pub as_sdt: Option<String>,
    /// Page number (0-based)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
    /// Results per page (max 20)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub num: Option<i64>,
}

/// Parameters for [`SearchParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct SearchParams {
    /// Search query (supports Google operators)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub q: Option<String>,
    /// Country code
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gl: Option<String>,
    /// Language code
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hl: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub num: Option<i64>,
    /// Page offset (0, 10, 20...)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub start: Option<i64>,
    /// Google domain
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    /// Device target: desktop, mobile, iphone, android, tablet
    #[serde(skip_serializing_if = "Option::is_none")]
    pub device: Option<SearchDevice>,
    /// Custom User-Agent (overrides device)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub user_agent: Option<String>,
    /// Response format: json (parsed) or html (raw SERP)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output: Option<SearchOutput>,
    /// City-level geo-targeting
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    /// Language restrict (e.g. lang_en)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lr: Option<String>,
    /// Time filter (e.g. qdr:d)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tbs: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub safe: Option<String>,
    /// UULE encoded location
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uule: Option<String>,
    /// Show omitted results
    #[serde(skip_serializing_if = "Option::is_none")]
    pub filter: Option<i64>,
    /// Disable auto-correction
    #[serde(skip_serializing_if = "Option::is_none")]
    pub nfpr: Option<i64>,
    /// Country restrict
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cr: Option<String>,
    /// Google Place CID
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ludocid: Option<String>,
    /// Knowledge Graph map ID
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lsig: Option<String>,
    /// Knowledge Graph entity ID
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kgmid: Option<String>,
    /// Cached search params
    #[serde(skip_serializing_if = "Option::is_none")]
    pub si: Option<String>,
    /// Layout control
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ibp: Option<String>,
    /// Google filter string
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uds: Option<String>,
    /// Chase deferred AI Overview page_token with a follow-up fetch and merge the result. Adds ~1s and 1 credit when the SERP defers the overview.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ai_overview: Option<bool>,
}

/// Parameters for [`ShoppingSearchParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ShoppingSearchParams {
    /// Product search query
    #[serde(skip_serializing_if = "Option::is_none")]
    pub q: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gl: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_price: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_price: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sort_by: Option<String>,
}

/// Parameters for [`ShortsSearchParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ShortsSearchParams {
    /// Search query
    #[serde(skip_serializing_if = "Option::is_none")]
    pub q: Option<String>,
    /// Country code
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gl: Option<String>,
    /// Language code
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hl: Option<String>,
    /// Google domain
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    /// Results per page
    #[serde(skip_serializing_if = "Option::is_none")]
    pub num: Option<i64>,
    /// Pagination offset
    #[serde(skip_serializing_if = "Option::is_none")]
    pub start: Option<i64>,
}

/// Parameters for [`TrendsAutocompleteParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct TrendsAutocompleteParams {
    /// Query prefix to resolve into Trends topics
    #[serde(skip_serializing_if = "Option::is_none")]
    pub q: Option<String>,
    /// Language code
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hl: Option<String>,
    /// Timezone offset in minutes
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tz: Option<String>,
}

/// Parameters for [`TrendsInterestParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct TrendsInterestParams {
    /// Search terms
    #[serde(skip_serializing_if = "Option::is_none")]
    pub q: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub geo: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
}

/// Parameters for [`TrendsRegionsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct TrendsRegionsParams {
    /// Search term
    #[serde(skip_serializing_if = "Option::is_none")]
    pub q: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub geo: Option<String>,
}

/// Parameters for [`TrendsRelatedParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct TrendsRelatedParams {
    /// Search term
    #[serde(skip_serializing_if = "Option::is_none")]
    pub q: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub geo: Option<String>,
}

/// Parameters for [`TrendsTrendingParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct TrendsTrendingParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub geo: Option<String>,
}

/// Parameters for [`VideosSearchParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct VideosSearchParams {
    /// Video search query
    #[serde(skip_serializing_if = "Option::is_none")]
    pub q: Option<String>,
    /// Country code
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gl: Option<String>,
    /// Language code
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hl: Option<String>,
    /// Time filter (e.g. qdr:d)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tbs: Option<String>,
    /// Safe search
    #[serde(skip_serializing_if = "Option::is_none")]
    pub safe: Option<String>,
    /// Page number
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
}
