// @generated by `cargo run -p xtask -- gen` from specs/ebay.json — do not edit by hand.
#![allow(clippy::all)]
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    non_snake_case,
    rustdoc::all
)]

use crate::core::{Client, Error, Method, QueryParams, Result};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;

/// Handle for the `ebay` platform. Obtain via [`crate::ScrapeBadger::ebay`].
#[derive(Clone)]
pub struct Ebay {
    client: Client,
}

impl Ebay {
    pub(crate) fn new(client: Client) -> Self {
        Self { client }
    }

    /// Access the underlying transport client.
    pub fn client(&self) -> &Client {
        &self.client
    }

    /// Keyword suggestions
    ///
    /// Return eBay keyword autocomplete suggestions.
    /// `GET /v1/ebay/autocomplete`
    pub async fn autocomplete(&self, params: AutocompleteParams) -> Result<Value> {
        let path = "/v1/ebay/autocomplete".to_string();
        let mut q = QueryParams::new();
        q.opt("query", params.query.as_ref());
        q.opt("domain", params.domain.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// List categories
    ///
    /// List eBay's top-level category ids.
    /// `GET /v1/ebay/categories`
    pub async fn list_categories(&self, params: ListCategoriesParams) -> Result<Value> {
        let path = "/v1/ebay/categories".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Browse a category
    ///
    /// List active listings within an eBay category.
    /// `GET /v1/ebay/categories/{category_id}/items`
    pub async fn browse_category(
        &self,
        category_id: impl AsRef<str>,
        params: BrowseCategoryParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/ebay/categories/{category_id}/items",
            category_id = category_id.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("domain", params.domain.as_ref());
        q.opt("page", params.page.as_ref());
        q.opt("per_page", params.per_page.as_ref());
        q.opt("sort_by", params.sort_by.as_ref());
        q.opt("min_price", params.min_price.as_ref());
        q.opt("max_price", params.max_price.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Completed / sold listings
    ///
    /// Search completed/sold listings — eBay's sold-price history.
    /// `GET /v1/ebay/completed`
    pub async fn completed(&self, params: CompletedParams) -> Result<Value> {
        let path = "/v1/ebay/completed".to_string();
        let mut q = QueryParams::new();
        q.opt("query", params.query.as_ref());
        q.opt("domain", params.domain.as_ref());
        q.opt("category_id", params.category_id.as_ref());
        q.opt("page", params.page.as_ref());
        q.opt("per_page", params.per_page.as_ref());
        q.opt("sort_by", params.sort_by.as_ref());
        q.opt("condition", params.condition.as_ref());
        q.opt("min_price", params.min_price.as_ref());
        q.opt("max_price", params.max_price.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get item detail
    ///
    /// Get a single eBay listing's full detail.
    /// `GET /v1/ebay/items/{item_id}`
    pub async fn get_item(&self, item_id: impl AsRef<str>, params: GetItemParams) -> Result<Value> {
        let path = format!("/v1/ebay/items/{item_id}", item_id = item_id.as_ref());
        let mut q = QueryParams::new();
        q.opt("domain", params.domain.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get item reviews
    ///
    /// Get catalog product reviews shown on an eBay listing.
    /// `GET /v1/ebay/items/{item_id}/reviews`
    pub async fn get_item_reviews(
        &self,
        item_id: impl AsRef<str>,
        params: GetItemReviewsParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/ebay/items/{item_id}/reviews",
            item_id = item_id.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("domain", params.domain.as_ref());
        q.opt("page", params.page.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// List markets
    ///
    /// List all supported eBay marketplaces.
    /// `GET /v1/ebay/markets`
    pub async fn list_markets(&self, params: ListMarketsParams) -> Result<Value> {
        let path = "/v1/ebay/markets".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Search listings
    ///
    /// Search an eBay marketplace for active listings.
    /// `GET /v1/ebay/search`
    pub async fn search(&self, params: SearchParams) -> Result<Value> {
        let path = "/v1/ebay/search".to_string();
        let mut q = QueryParams::new();
        q.opt("query", params.query.as_ref());
        q.opt("domain", params.domain.as_ref());
        q.opt("category_id", params.category_id.as_ref());
        q.opt("page", params.page.as_ref());
        q.opt("per_page", params.per_page.as_ref());
        q.opt("sort_by", params.sort_by.as_ref());
        q.opt("condition", params.condition.as_ref());
        q.opt("buying_format", params.buying_format.as_ref());
        q.opt("min_price", params.min_price.as_ref());
        q.opt("max_price", params.max_price.as_ref());
        q.opt("free_shipping", params.free_shipping.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get seller profile
    ///
    /// Get an eBay seller's public profile.
    /// `GET /v1/ebay/sellers/{username}`
    pub async fn get_seller(
        &self,
        username: impl AsRef<str>,
        params: GetSellerParams,
    ) -> Result<Value> {
        let path = format!("/v1/ebay/sellers/{username}", username = username.as_ref());
        let mut q = QueryParams::new();
        q.opt("domain", params.domain.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get seller feedback
    ///
    /// Get a seller's recent feedback comments.
    /// `GET /v1/ebay/sellers/{username}/feedback`
    pub async fn get_seller_feedback(
        &self,
        username: impl AsRef<str>,
        params: GetSellerFeedbackParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/ebay/sellers/{username}/feedback",
            username = username.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("domain", params.domain.as_ref());
        q.opt("page", params.page.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }

    /// Get seller listings
    ///
    /// List the active listings of a single eBay seller.
    /// `GET /v1/ebay/sellers/{username}/items`
    pub async fn get_seller_items(
        &self,
        username: impl AsRef<str>,
        params: GetSellerItemsParams,
    ) -> Result<Value> {
        let path = format!(
            "/v1/ebay/sellers/{username}/items",
            username = username.as_ref()
        );
        let mut q = QueryParams::new();
        q.opt("domain", params.domain.as_ref());
        q.opt("query", params.query.as_ref());
        q.opt("page", params.page.as_ref());
        q.opt("per_page", params.per_page.as_ref());
        let query = q.into_pairs();
        let body = None;
        self.client.send(Method::GET, &path, &query, body).await
    }
}

// ===== Models =====

/// Parameters for [`AutocompleteParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct AutocompleteParams {
    /// Partial query prefix
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
}

/// Parameters for [`ListCategoriesParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ListCategoriesParams {}

/// Parameters for [`BrowseCategoryParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct BrowseCategoryParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub per_page: Option<i64>,
    /// best_match|ending_soonest|newly_listed|price_low_to_high|price_high_to_low
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sort_by: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_price: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_price: Option<f64>,
}

/// Parameters for [`CompletedParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct CompletedParams {
    /// Search keywords
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub category_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub per_page: Option<i64>,
    /// best_match|ending_soonest|newly_listed|price_low_to_high|price_high_to_low
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sort_by: Option<String>,
    /// new|open_box|refurbished|used|for_parts
    #[serde(skip_serializing_if = "Option::is_none")]
    pub condition: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_price: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_price: Option<f64>,
}

/// Parameters for [`GetItemParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetItemParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
}

/// Parameters for [`GetItemReviewsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetItemReviewsParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
}

/// Parameters for [`ListMarketsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ListMarketsParams {}

/// Parameters for [`SearchParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct SearchParams {
    /// Search keywords
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    /// Marketplace domain (com, co.uk, de …)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    /// Restrict to a category id
    #[serde(skip_serializing_if = "Option::is_none")]
    pub category_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
    /// 60, 120 or 240
    #[serde(skip_serializing_if = "Option::is_none")]
    pub per_page: Option<i64>,
    /// best_match|ending_soonest|newly_listed|price_low_to_high|price_high_to_low
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sort_by: Option<String>,
    /// new|open_box|refurbished|used|for_parts
    #[serde(skip_serializing_if = "Option::is_none")]
    pub condition: Option<String>,
    /// auction|buy_it_now|best_offer
    #[serde(skip_serializing_if = "Option::is_none")]
    pub buying_format: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_price: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_price: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub free_shipping: Option<bool>,
}

/// Parameters for [`GetSellerParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetSellerParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
}

/// Parameters for [`GetSellerFeedbackParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetSellerFeedbackParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
}

/// Parameters for [`GetSellerItemsParams`]. All fields optional; required ones are noted per method.
#[derive(Debug, Clone, Default, Serialize)]
pub struct GetSellerItemsParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub per_page: Option<i64>,
}
